ci.sh, resources/rsync-tools.sh, resources/util.sh
This CI work takes all the .keyboard_info files and adds them into a ZIP so that api.keyman.com backend can easily grab them when it needs for building its search database.
=> Deploy keyboard_info data as a zip to downloads.keyman.com for consumption by api.keyman.com

ci.sh
Two things:
* The minKeymanDesktopVersion field was renamed to minKeymanVersion. This updates ci.sh to use the new name
* Also build combined installer for Windows only if the kmp supports Windows.
=> CI: minKeymanVersion and combined installer for Windows only if package suppports Windows

release/gff/gff_tigrinya_eritrea/gff_tigrinya_eritrea.keyboard_info
=> [gff_tigrinya_eritrea] add region to BCP47 tag in .keyboard_info

release/k/khmer_angkor/HISTORY.md, release/k/khmer_angkor/khmer_angkor.kpj, release/k/khmer_angkor/source/khmer_angkor.kmn, release/k/khmer_angkor/source/khmer_angkor.kps
In order to use `khmer_angkor.kmp` as an example for [mobile keyboard distribution documentation](https://help.keyman.com/developer/10.0/guides/distribute/mobile-packages), we should add the .js file to the keyboard package.
* Also rev version from 1.0.1 to 1.0.2
=> [khmer_ankor] Add touch keyboard to keyboard package

experimental/n/ntl_onekey/ntl_onekey.keyboard_info
I've added a name (in Chinese) for the NTL OneKey keyboard to the keyboard_info file.
=> Add keyboard name for NTL OneKey in keyboard_info file

legacy/k/khowar/source/help/khowar.php
The Unix-style line endings resulted in https://help.keyman.com/keyboard showing
```
Khowar Keyboard Help';
$pagetitle = 'Khowar
```
=> [khowar] Use Windows line endings for help file

release/packages/syriac_aramaic/source/help/syriac_aramaic.php
I realized there is a link to a non-existent help file. So, this is a minimal file that points to the 3 keyboard layouts.
=> [syriac_aramaic-help] Added minimal help file with links to layouts

release/sil/sil_philippines/HISTORY.md, release/sil/sil_philippines/README.md, release/sil/sil_philippines/sil_philippines.keyboard_info, release/sil/sil_philippines/source/help/sil_philippines.php, release/sil/sil_philippines/source/readme.htm, release/sil/sil_philippines/source/sil_philippines.kmn, release/sil/sil_philippines/source/welcome/welcome.htm
Also changed "Andika New Basic" to "Andika" since ANB does not have barred yY in the font.
=> [sil_philippines] Remove statement about US keyboard

release/sil/sil_uganda_tanzania/source/sil_uganda_tanzania.kmn
It should have been version 1.1. Other documentation is correct.
=> [sil_uganda_tanzania] Change version number

release/sil/sil_yi/HISTORY.md, release/sil/sil_yi/README.md, release/sil/sil_yi/sil_yi.kpj, release/sil/sil_yi/source/readme.htm, release/sil/sil_yi/source/sil_yi.kmn, release/sil/sil_yi/source/sil_yi.kps
This fix is based on comment from @mhosken: I've found a bug in the SIL Yi keyboard. `'rryx' + " "` should map to `U+A38F` but there is a typo mapping it to `U+A39F`.
=> [sil_yi] correct output for rryx

release/rac/rac_hindko/rac_hindko.keyboard_info
After #563 , the CI build is failing because `rac_hindko.keyboard_info` is missing.
This PR reverts the file from #356
=> [rac_hindko] Revert rac_hindko.keyboard_info file

release/sil/sil_tawallammat/source/welcome/welcome.htm
The ralt image in welcome.htm isn't visible on case-sensitive systems
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/keymanapp/keyboards/571)
=> [sil_tawallammat] case in welcome.htm for ralt image

release/l/lao_2008_basic/lao_2008_basic.keyboard_info
The keyboard uses saysettha_ot.ttf so update keyboard_info file.
c.f. https://github.com/sillsdev/keyman-s.keyman.com/pull/46
=> [lao_2008_basic] Associate saysettha_ot.ttf font

release/g/galaxie_greek_positional/source/help/galaxie_greek_positional.php
Keyboard: [Galaxie Greek (Phonetic)](https://keyman.com/keyboards/galaxie_greek_positional)
System: Arch Linux, Keyman 11.0.105.
The help file explains typing "ὧμέγα" as `w"[[me/ga` which in fact produces "ὧ῾μέγα", i.e. second "[" is excessive. Could it be a typo or specific behavior of the linux port?
P.S. Searching though the whole repository, finds "ὧμέγα" in several other keyboard layouts probably needed to be fixed too.
=> Update Galaxie Greek (Phonetic) help

build.sh
The `build.sh` script as it is now failed to build the layouts on Linux for me. This small patch changes how `KMCOMP_LAUNCHER` is defined: instead of only setting the value to `wine` on darwin, it will only be left empty on Windows and set to `wine` on all other platforms.
=> [infrastructure] Always use wine when not on Windows

.gitignore, build.sh, resources/compile.sh, resources/util.sh
Fixes:
* Bash output being cleared on finish of script on Windows
* Single character parameters not being applied
* Build of single keyboard targets
Supports:
* Build of just keyboard or just package with -T
* Ignoring tests/ folders in release/k/keyboard/
* Cleaning tests/ folders when using -c
=> [Infrastructure] Improve support for regression tests

release/fv/fv_gwichin/HISTORY.md, release/fv/fv_gwichin/LICENSE.md, release/fv/fv_gwichin/README.md, release/fv/fv_gwichin/source/fv_gwichin.kmn, release/fv/fv_gwichin/source/fv_gwichin.kps, release/fv/fv_han/HISTORY.md, release/fv/fv_han/LICENSE.md, release/fv/fv_han/README.md, release/fv/fv_han/source/fv_han.kmn, release/fv/fv_han/source/fv_han.kps, release/fv/fv_northern_tutchone/HISTORY.md, release/fv/fv_northern_tutchone/LICENSE.md, release/fv/fv_northern_tutchone/README.md, release/fv/fv_northern_tutchone/source/fv_northern_tutchone.kmn, release/fv/fv_northern_tutchone/source/fv_northern_tutchone.kps, release/fv/fv_southern_tutchone/HISTORY.md, release/fv/fv_southern_tutchone/LICENSE.md, release/fv/fv_southern_tutchone/README.md, release/fv/fv_southern_tutchone/source/fv_southern_tutchone.kmn, release/fv/fv_southern_tutchone/source/fv_southern_tutchone.kps, release/fv/fv_tagizi_dene/HISTORY.md, release/fv/fv_tagizi_dene/LICENSE.md, release/fv/fv_tagizi_dene/README.md, release/fv/fv_tagizi_dene/source/fv_tagizi_dene.kmn, release/fv/fv_tagizi_dene/source/fv_tagizi_dene.kps, release/h/hieroglyphic/HISTORY.md, release/h/hieroglyphic/LICENSE.md, release/h/hieroglyphic/README.md, release/h/hieroglyphic/source/hieroglyphic.kmn, release/h/hieroglyphic/source/hieroglyphic.kps
The keyboards impacted were:
* fv_gwichin
* fv_han
* fv_northern_tutchone
* fv_southern_tutchone
* fv_tagizi_dene
* hieroglyphic
=> [meta] Increment version numbers on keyboards that were impacted by Chrome compatibility issue #183 to force redeployment

release/itrans/itrans_roman/HISTORY.md, release/itrans/itrans_roman/itrans_roman.kpj, release/itrans/itrans_roman/source/extras/test_ipa_vowels.xml, release/itrans/itrans_roman/source/help/itrans_roman.php, release/itrans/itrans_roman/source/itrans_roman.kmn, release/itrans/itrans_roman/source/itrans_roman.kps, release/itrans/itrans_roman/source/welcome/welcome.htm
also removes the font-family in help files, page was not displaying OK on Mac OS.
=> [itrans_roman] Version 1.1.1 add IPA vowels - map to lowercase characters

release/basic/basic_kbdarmph/source/help/basic_kbdarmph.php, release/basic/basic_kbddzo/source/help/basic_kbddzo.php
Mobile layout was not displaying rightalt-shift layer. I think these are now correct.
=> [basic-help] adjust name of rightalt-shift to shift-alt and shift-ralt

release/fv/fv_gwichin/HISTORY.md, release/fv/fv_gwichin/README.md, release/fv/fv_gwichin/source/fv_gwichin.keyman-touch-layout, release/fv/fv_gwichin/source/fv_gwichin.kmn, release/fv/fv_gwichin/source/fv_gwichin.kvks, release/fv/fv_gwichin/source/help/fv_gwichin.php, release/fv/fv_gwichin/source/welcome/welcome.htm
I also added ` and ^ to the mobile layout so they could type grave and circumflex on mobile since they can type them on desktop.
=> [fv_gwichin] use canonical ordering below mark then above mark (ogonek and grave)

legacy/u/uzbek/DEPRECATED.md, release/basic/basic_kbduzb/basic_kbduzb.keyboard_info
I neglected to associate the legacy "uzbek" keyboard as deprecated.
No need for version bump.
=> [basic_kbduzb-dep] Deprecate uzbek keyboard also

release/basic/basic_kbdmyan/basic_kbdmyan.keyboard_info, release/basic/basic_kbdus/basic_kbdus.keyboard_info
Windows has some duplicate keyboards under different names. This is an attempt to document that.
=> [basic_us_myan] List duplicate keyboards from Windows

resources/s-keyman-com.sh
This should reduce the frequency of CI builds failing because s.keyman.com is updated between the build starting and the build pushing changes upstream to origin, by updating the local clone of s.keyman.com immediately before adding changes.
=> Ensure s.keyman.com clone is up to date before pushing changes (reduces risk of CI failing)

release/a/aksarabali_panlex/HISTORY.md, release/a/aksarabali_panlex/README.md, release/a/aksarabali_panlex/source/aksarabali_panlex.kmn, release/a/aksarabali_panlex/source/welcome/welcome.htm
Adds support for typing ulu plus suku after a consonant. This is an illicit combination of vowel marks, but it is actually attested in palm leaf manuscripts as a way to indicate that an aksara was a mistake and should be ignored. So the keyboard needs to support it!
=> [aksarabali_panlex] implement alt + dependent vowel combos; update docs

build.sh, resources/compile.sh
This is a dependency for the FirstVoices apps builds.
=> [Infrastructure] Support building just a shortname-group of keyboards

release/k/krung/HISTORY.md, release/k/krung/README.md, release/k/krung/source/krung.kmn, release/k/krung/source/krung.kvks
This addresses issues in on screen keyboards arising from keymanapp/keyman#1460. The good news is that only Krung was impacted negatively. The only other keyboard in the **release/** folder listed in that issue is **sil_cameroon_qwerty**, but it turns out the OSK is correct as in the source. The remaining keyboards from the issue are all in the **legacy/** folder, which means they are not rebuilt so the compiler update will not impact them.
=> [Krung] Fixup missing symbols from krung.kvks

resources/help-keyman-com.sh
This will help prevent errors where help.keyman.com is updated while a build is in progress, for example https://build.palaso.org/viewLog.html?buildId=163030&buildTypeId=Keyboards_Upload
Changes easier to see if you use the cog to select 'ignore whitespace'
=> [Meta] Reduce CI failures by ensuring help.keyman.com is locally up-to-date before pushing

legacy/m/marathi/DEPRECATED.md, legacy/m/marathi_kab/DEPRECATED.md, release/basic/basic_kbdinmar/basic_kbdinmar.keyboard_info
Deprecating two keyboards. No version bump needed.
=> [inscript-marathi] Deprecate KAB Marathi keyboards

legacy/f/farsi_kab/DEPRECATED.md, release/basic/basic_kbdfa/basic_kbdfa.keyboard_info
Deprecate one keyboard. No version bump needed.
=> [inscript-farsi] Deprecate Farsi KAB Inscript keyboard

ci.sh, resources/util.sh
This will allow the keyboards build to generate only the .kmp and .js targets when doing the initial upload. Bundled installers will be built on demand.
Part of https://github.com/keymanapp/keyman/issues/2248
=> [ci] Add support for building and uploading a single executable installer

release/gff/gff_geez/HISTORY.md, release/gff/gff_geez/README.md, release/gff/gff_geez/gff_geez.kpj, release/gff/gff_geez/source/gff_geez.kmn, release/gff/gff_geez/source/gff_geez.kps
Fix for number input sequence for orders of 10 -one cycle was missing.  The numeral input statements are synched with gff_amharic.
=> gff_geez v1.4

release/packages/galaxie_greek_hebrew_mnemonic/galaxie_greek_hebrew_mnemonic.kpj, release/packages/galaxie_greek_hebrew_mnemonic/source/galaxie_greek_hebrew_mnemonic.kps, release/packages/galaxie_greek_hebrew_positional/galaxie_greek_hebrew_positional.kpj, release/packages/galaxie_greek_hebrew_positional/source/galaxie_greek_hebrew_positional.kps, release/packages/gff_amh_powerpack_7/gff_amh_powerpack_7.kpj, release/packages/gff_amh_powerpack_7/source/gff_amh_powerpack_7.kps, release/packages/syriac_aramaic/source/syriac_aramaic.kps, release/packages/syriac_aramaic/syriac_aramaic.kpj
Fixes keymanapp/keyman#2338.
The dependencies for release packages were referring to other paths.
The pattern for the packages folder is to include the source kmn files
in the project so that they will be built along with the package.
However, the .kps files themselves still referred to the built kmx/js
in the original folders, rather than the expected ..\build\ path.
Given this change is a compile-phase-only change, there is no need to
update version numbers or make new releases.
This will fix the situation where bundled release package installers
are failing to build.
Note: I originally started off thinking we'd need to add a dependency
file into the keyboard folders that had dependencies and build those 
dependencies first, but this is a cleaner fix that avoids 
infrastructure that …
=> fix(ci): dependencies for release packages

ci.sh
This is a partial fix to a race condition in our build. When we are
doing a release build of Keyman Desktop, the files are uploaded to
downloads.keyman.com as the final step. While the files are uploading,
there is a window of time where the downloads.keyman.com version API
(e.g. https://downloads.keyman.com/api/version/windows/2.0) starts to
return the new version, but the new version is not yet fully uploaded.
Normally, this would be a tiny issue that at worst would result in a
failed download for a single user if they happened to download within
that second. It wouldn't necessarily be something to be concerned about.
Now that we have bundled installers building on a download trigger, this
caused a fun issue. The build agent started a bundled build for the new
version, and requested …
=> fix: fail ci early if assets unavailable

release/fv/fv_dakelh/README.md
PR #927 restored a previous version of the touch layout. There were some minor questions about the layout which were not addressed in that PR, but are added to the README.md file by this PR so they will be preserved should for any future work on this keyboard.
=> [fv_dakelh] preserve comments from PR for future work

release/h/haroi/HISTORY.md, release/h/haroi/README.md, release/h/haroi/haroi.keyboard_info, release/h/haroi/haroi.kpj, release/h/haroi/source/haroi.kmn, release/h/haroi/source/haroi.kps, release/h/haroi/source/help/haroi.php, release/h/haroi/source/readme.htm, release/h/haroi/source/welcome/welcome.htm
This PR applies @tim-eves ' fixes which address a user's issue where the Haroi Keyman keyboard is handling NFC vowels, but the Flex application is NFD.
The key sequence `to68ng` should result in `tô̆ng` but Flex was rendering `tô8ng`
* Also added the fully-specified language tag `hro-Latn-VN`.
Tested on Windows 10, Flex 9.0 RC and Keyman Desktop 12.0.64.0
=> [haroi] Add additional rules to handle either NFC or NFD vowels

release/packages/fv_all/HISTORY.md, release/packages/fv_all/README.md, release/packages/fv_all/build.sh, release/packages/fv_all/fv_all.keyboard_info
Currently, fv_all/build.sh gathers First Voices .kmx keyboards into a single package.
For Keyman 14, the mobile apps will be dealing strictly with .kmp keyboard packages.
This PR updates the build.sh script to also include touch layout keyboards needed for the mobile First Voices app.
=> [fv_all] Add JS keyboards to FirstVoices keyboard package

release/k/khmer_angkor/khmer_angkor.keyboard_info
Addresses keymanapp/keyman#2977
The OSK for khmer_angkor isn't rendering on older Android devices.
The keyboard package includes the Mondulkiri font, but the cloud server doesn't deliver it.
See also keymanapp/s.keyman.com#20
This updates the keyboard_info file to associate the Mondulriki font.
=> [khmer_angkor] Add Mondulkiri font to keyboard_info

legacy/b/bod/bod.keyboard_info, legacy/b/bod_transliterating/bod_transliterating.keyboard_info
Documentation (https://help.keyman.com/developer/cloud/keyboard_info/1.0/) indicates this is necessary for packages in the legacy folder:
> string, filename of the .kmp file that will be distributed, relative to the keyboard base folder, including extension, required for experimental/ and legacy/ folders. If no .kmp exists, then keyboard is js only. For release/ folders, this must be id/build/id.kmp.
=> [bod] Take 3 - Adding packageFilename to keyboard_info

release/nrc/nrc_crk_cans/HISTORY.md, release/nrc/nrc_crk_cans/nrc_crk_cans.kpj, release/nrc/nrc_crk_cans/source/nrc_crk_cans.keyman-touch-layout, release/nrc/nrc_crk_cans/source/nrc_crk_cans.kmn, release/nrc/nrc_crk_cans/source/nrc_crk_cans.kps
This changes the Y-final, as in #1258, and also adds rare nwV syllabics that were missing from the previous versions of this keyboard.
=> [nrc_crk_cans] fix Y final; add rare nwV syllabics

legacy/b/bengali_inscript/source/help/chart.php, legacy/e/ekwbamuni/source/help/chart.php, legacy/e/ekwbamuni/source/help/ekwbamuni.php, legacy/e/ekwbamuni/source/help/srii/tamil_srii.php, legacy/e/ekwnewtwuni/source/help/chart.php, legacy/e/ekwnewtwuni/source/help/ekwnewtwuni.php, legacy/e/ekwnewtwuni/source/help/srii/tamil_srii.php, legacy/e/ekwtamil99uniext/source/help/chart.php, legacy/e/ekwtamil99uniext/source/help/ekwtamil99uniext.php, legacy/e/ekwtamil99uniext/source/help/srii/tamil_srii.php, legacy/e/ekwunitamil/source/help/chart.php, legacy/e/ekwunitamil/source/help/srii/tamil_srii.php, legacy/isis/isis_tamil/source/help/tamil_srii.php, legacy/k/khowar/source/help/khowar.php, legacy/t/tamil/source/help/chart.php, legacy/t/tamil/source/help/srii/tamil_srii.php, legacy/t/tamil/source/help/tamil.php, legacy/v/visual_media_tamil_modular/source/help/chart.php, legacy/v/visual_media_tamil_modular/source/help/srii/tamil_srii.php, legacy/v/visual_media_tamil_modular/source/help/visual_media_tamil_modular.php, legacy/v/visual_media_tamil_typewriter/source/help/chart.php, legacy/v/visual_media_tamil_typewriter/source/help/srii/tamil_srii.php, legacy/v/visual_media_tamil_typewriter/source/help/visual_media_tamil_typewriter.php, release/e/ekwtamil99uni/source/help/chart.php, release/e/ekwtamil99uni/source/help/ekwtamil99uni.php, release/e/ekwtamil99uni/source/help/srii/tamil_srii.php
Depends on keymanapp/help.keyman.com#200
The primary objective of this PR was to remove references to the legacy `$site_tavultesoft` variable which was causing site errors. The global variable `$keyman_com` will be available for use to refer to https://keyman.com once PR 200 referenced above is merged.
Version numbers do not need to be updated because the php files are updated on help.keyman.com with every deployment.
=> fix: remove obsolete server references in php files

release/sil/sil_euro_latin/HISTORY.md, release/sil/sil_euro_latin/source/sil_euro_latin.kmn, release/sil/sil_euro_latin/source/sil_euro_latin.kps
I missed this during the review
#1162 added DejaVu Sans font to the keyboard package.
The package source file needs to use it as OSKFont and DisplayFont.
The keyboard rendered fine in the emulator. But this is good for completeness.
=> [sil_euro_latin] Assign font in keyboard package

release/q/quinault/HISTORY.md, release/q/quinault/LICENSE.md, release/q/quinault/README.md, release/q/quinault/quinault.keyboard_info, release/q/quinault/quinault.kpj, release/q/quinault/source/help/quinault.php, release/q/quinault/source/quinault.keyman-touch-layout, release/q/quinault/source/quinault.kmn, release/q/quinault/source/quinault.kps, release/q/quinault/source/readme.htm, release/q/quinault/source/welcome/welcome.htm
Also renamed `quinault-layout.js` to `quinault.keyman-touch-layout` to follow modern conventions.
=> [quinault] Updated mobile layout to be able to access shift layer

legacy/n/ndailu keyman keyboard/DEPRECATED.md, release/n/ntl_onekey/ntl_onekey.keyboard_info
@sdysart created `legacy/ndalu keyman keyboard`  4 years ago. A user recently reported a bug:
> ndailu keyman keyboard has an error where typing <kbd>g</kbd>+<kbd>g</kbd> should give you U+19B6 but gives two U+19B5.  `release/n/ntl_onekey` is a dailu keyboard that produces the proper U+19B6 character when typing <kbd>w</kbd>+<kbd>w</kbd>
Rather than updating a legacy (desktop only) keyboard, @sdysart wants to deprecate it in favor of ntl_onekey. ntl_onekey also has the added benefit of including a touch layout.
Question: ndali keyman keyboard uses a language tag `khb` and ntl_oneykey uses `khb-Talu`. Maybe we need to add `khb` to ntl_onekey?
=> Deprecating "ndailu keyman keyboard"

resources/codesign.sh
Removes sha1 signing and hands signing over to agent on Keyman build agents for Windows bundled installers.
=> chore: update code signing

release/sil/sil_devanagari_phonetic/source/help/sil_devanagari_phonetic.php
Using the Annapurna font (a legacy font) instead of Annapurna SIL (Unicode) was causing wrong character display IF Annapurna was installed.
=> [sil_deva_help] Change font call from Annapurna to Annapurna SIL

release/basic/basic_kbdmyan/HISTORY.md, release/basic/basic_kbdmyan/LICENSE.md, release/basic/basic_kbdmyan/README.md, release/basic/basic_kbdmyan/basic_kbdmyan.keyboard_info, release/basic/basic_kbdmyan/basic_kbdmyan.kpj, release/basic/basic_kbdmyan/source/basic_kbdmyan.kmn, release/basic/basic_kbdmyan/source/basic_kbdmyan.kps, release/basic/basic_kbdmyan/source/readme.htm, release/basic/basic_kbdmyan/source/welcome/welcome.htm
* the Padauk font to the .kmp
* update metadata
* bump version number to 1.2
Before the fix:
After the fix:
=> [basic_kbdmyan] fix font issues

release/sil/sil_kmhmu/HISTORY.md, release/sil/sil_kmhmu/README.md, release/sil/sil_kmhmu/sil_kmhmu.kpj, release/sil/sil_kmhmu/source/sil_kmhmu.kmn
This version updates to include the two special characters in the Lao consonant  store (`store(Consonant)`) so that the rules for Thin Space and Full Space are triggered and work as expected. 
The previous version would not add a half space after the two characters ໞ (on Shift + Y) and ໟ (on Shift + U) when the spacebar is pressed.
We would like to ensure as well whether the two fonts get installed when the .kmp is either installed via the Keyman Desktop configuration or via keyman.com.
=> [sil_kmhmu] half space after the special two

release/bj/bj_naskapi_classic/HISTORY.md, release/bj/bj_naskapi_classic/README.md, release/bj/bj_naskapi_classic/bj_naskapi_classic.kpj, release/bj/bj_naskapi_classic/source/bj_naskapi_classic.kmn, release/bj/bj_naskapi_classic/source/bj_naskapi_classic.kps
I suggested we not have a mobile layout for this keyboard, but I forgot we are not supposed to include .js when there is no mobile layout so I approved it.
This PR removes the .js file from the keyboard and bumps the version. No other changes.
=> [bj_naskapi_classic] Remove .js from package and bump version

experimental/t/taigi_poj/HISTORY.md, experimental/t/taigi_poj/README.md, experimental/t/taigi_poj/source/taigi_poj.kmn, experimental/t/taigi_poj/source/taigi_poj.kps, experimental/t/taigi_poj/source/taigi_poj.kvks, experimental/t/taigi_poj/taigi_poj.kpj
The e͘ character is used in some Taiwanese dialects/accents, referred to as Lāi-po͘-khiuⁿ or Chiang-chiu-khiuⁿ, for example in Gî-lân (Yilan, 宜蘭).
=> [taigi_poj] Add support for e͘

release/h/haroi/HISTORY.md, release/h/haroi/haroi.keyboard_info, release/h/haroi/haroi.kpj, release/h/haroi/source/haroi.kmn, release/h/haroi/source/haroi.kps, release/h/haroi/source/help/haroi.php, release/h/haroi/source/welcome/welcome.htm
Fixes keymanapp/keyboards#1392
* Add additional rules for handling combining overline
* Also removes language tag `hro-Latn-VN` (Keyman Developer 14.0 flags it as not being canonical)
Keyboard still undergoing tests
=> [haroi] Add rules for combining overline

build.sh, resources/merge.sh
Fixes keymanapp/api.keyman.com#136.
Instead of using the date of the build, we now use the last changed date for the folder according to the git log, which is significantly more useful!
For example, for gff_amharic.keyboard_info, this produces (snipped):
```json
{
"id": "gff_amharic",
"authorName": "The Ge'ez Frontier Foundation",
"authorEmail": "keyboards@ethiopic.org",
"lastModifiedDate": "2020-12-04T04:57:34Z",
"sourcePath": "release/gff/gff_amharic",
"version": "1.9.2",
"packageFilename": "gff_amharic.kmp"
}
```
instead of:
```json
{
"id": "gff_amharic",
"authorName": "The Ge'ez Frontier Foundation",
"authorEmail": "keyboards@ethiopic.org",
"lastModifiedDate": "2021-01-14T23:08:09.024Z",
"sourcePath": "release/gff/gff_amharic",
"version": "2.0",
"packageFilename": "gff_amharic.kmp"
} …
```
=> fix: use correct modification date

.gitignore, README.md, resources/compile.sh, resources/util.sh
Allows the build script to be restarted with `-start shortname/prefix` for example: `./build.sh -start sil/sil_eur` will start building all keyboards, alphabetically, beginning with `sil_euro_latin`. This helps when a keyboard fails to build, so you don't have to rebuild all the earlier keyboards again!
Adds some colour to make each keyboard built more visible.
=> chore: build script tweaks

release/fv/fv_gwichin/HISTORY.md, release/fv/fv_gwichin/LICENSE.md, release/fv/fv_gwichin/README.md, release/fv/fv_gwichin/source/fv_gwichin.kmn, release/fv/fv_gwichin/source/fv_gwichin.kps, release/fv/fv_southern_tutchone/HISTORY.md, release/fv/fv_southern_tutchone/LICENSE.md, release/fv/fv_southern_tutchone/README.md, release/fv/fv_southern_tutchone/source/fv_southern_tutchone.kmn, release/fv/fv_southern_tutchone/source/fv_southern_tutchone.kps
This PR addresses two of the five keyboards listed in issue #1375 
- The following keyboards have their version number incremented:
- fv_gwichin
- fv_southern_tutchone
- The following will be handled by whatever PR addresses issue 1237:
- fv_taltan
- fv_kwakwala_liqwala
- The following will be handled by whatever PR addresses issue 1384:
- fv_hlgaagilda_xaayda_kil
=> [fv_gwichin][fv_southern_tutchone]version bump

release/sil/sil_euro_latin/sil_euro_latin.keyboard_info
We want to merge the separate landing page for sil_euro_latin (https://keyman.com/eurolatin) as it is essentially the same content as the keyboard record. We thought we'd just add this blurb to the keyboard description :)
=> chore: add blurb from keyman.com to sil_euro_latin keyboard

release/sil/sil_eastern_congo/HISTORY.md, release/sil/sil_eastern_congo/README.md, release/sil/sil_eastern_congo/sil_eastern_congo.kpj, release/sil/sil_eastern_congo/source/sil_eastern_congo.kmn
Well, this keyboard has been a true mess. Sorry about this! I think it's finally correct.
Typing `''` to get `'` and ` `` ` to get ` was messed up when we tried to implement extra high and extra low tone. Then I forgot to revert two rules in the previous version.
=> [sil_eastern_congo] Fix bug introduced in previous version

release/h/hieroglyphic/HISTORY.md, release/h/hieroglyphic/hieroglyphic.keyboard_info, release/h/hieroglyphic/source/hieroglyphic.kmn, release/h/hieroglyphic/source/hieroglyphic.kps
While investigating keymanapp/keyman#4990 I was able to install hieroglyphic keyboard on Keyman for Android.
I wondered why:
1. The keyboard wasn't working (e.g Shift-H)
2. The bottom right key on the default layer had no output
Turns out the hieroglyphic keyboard should not be available on mobile apps though
https://keyman.com/keyboards/hieroglyphic lists:
hieroglyphic.kmn only targets 
```
store(&TARGETS) 'windows macosx linux web'
```
I suspect kmcomp sees the .js file in the .kmp file and erroneously includes Android and iOS.
This PR fixes the platforms that get listed in the keyboard_info file.
=> [hieroglyphic] Fix platforms in keyboard_info file

release/sil/sil_ethiopic/source/help/sil_ethiopic.php
#1544 
My previous attempt did not look as the Keyman help files are supposed to look. It just looked like an htm page without Keyman branding.
This one puts the Keyman help header info in there and hopefully will look better.
However, the tables will probably still need some scrolling as we see with: https://help.keyman.com/keyboard/sil_ethiopic_power_g
=> [fix_silEthi_php] Fix help file to look as expected by Keyman

release/gff/gff_gurage/HISTORY.md, release/gff/gff_gurage/README.md, release/gff/gff_gurage/gff_gurage.keyboard_info, release/gff/gff_gurage/gff_gurage.kpj, release/gff/gff_gurage/source/gff_gurage.kmn, release/gff/gff_gurage/source/gff_gurage.kps, release/packages/gff_gurage_and_amharic/HISTORY.md, release/packages/gff_gurage_and_amharic/README.md, release/packages/gff_gurage_and_amharic/gff_gurage_and_amharic.keyboard_info, release/packages/gff_gurage_and_amharic/gff_gurage_and_amharic.kpj, release/packages/gff_gurage_and_amharic/source/gff_gurage_and_amharic.kps
The only change to the keyboard file is the VERSION string is set to '10.0' from '14.0', which is erroneous and caused an issue on macOs (discussed in: https://github.com/keymanapp/keyboards/pull/1513#issuecomment-818269381).  The fix corresponds to the reported issue: https://github.com/keymanapp/keyman/issues/5316
I had made this error earlier with gff_amharic , I had actually updated gff_gurage evern earlier but did not submit it, then forgot about the VERSION string.
=> GFF Gurage v0.8.1

release/b/balochi_phonetic/HISTORY.md, release/b/balochi_phonetic/balochi_phonetic.kpj, release/b/balochi_phonetic/source/balochi_phonetic.kmn, release/b/balochi_phonetic/source/balochi_phonetic.kps
This was causing the .ttf to be excluded from the build, without warning or error.
I have opened a [corresponding issue](https://github.com/keymanapp/keyman/issues/5464) in Keyman Developer to improve validation of .kps files to avoid this in the future.
Picked up by chance in a conversation on Slack!
=> fix(balochi_phonetic): typo in .kps masking .ttf

build.sh, release/sil/sil_nubian/source/sil_nubian.kps, resources/compile.sh, resources/validate.sh, tools/kps.xsd
This adds xmllint checks for .kps file to the build. If xmllint is not on the path, then the XMLLINT variable can be set to point to it; if no xmllint can be found then .kps file structure validation will be skipped (not a failure).
Found minor errors in one .kps file (apart from balochi_phonetic, which is already resolved in a separate branch).
Relates to keymanapp/keyman#5464 and uses .xsd from keymanapp/api.keyman.com#158. Do not merge until api.keyman.com PR is approved (as we may need to propagate changes for the .xsd to this branch).
Note: I will update the build agents to ensure xmllint is available on them too.
=> feat: xmllint .kps files

experimental/t/taigi_poj/HISTORY.md, experimental/t/taigi_poj/README.md, experimental/t/taigi_poj/source/taigi_poj.kmn, experimental/t/taigi_poj/source/taigi_poj.kps, experimental/t/taigi_poj/taigi_poj.kpj
With the previous versions, it is impossible to type the syllable "nng", because "nn" is converted to "ⁿ".  This update only allows "ⁿ" to be typed after a vowel.  For example:
"nng5" -> "nn̂g"
"inn7" -> "īⁿ"
=> Taigi POJ v1.4: ⁿ only after vowels

release/sil/sil_euro_latin/source/sil_euro_latin_js.txt
Fixes keymanapp/keyman#5939.
The KeymanWeb_KeyHoverColor variable has not been defined in KeymanWeb for many years. So we should define it locally here.
=> fix(sil_euro_latin): use of KeymanWeb_KeyHoverColor

release/g/galaxie_greek_positional/galaxie_greek_positional.keyboard_info, release/sil/sil_greek_polytonic/sil_greek_polytonic.keyboard_info
See discussion at the end of #1708 . Twice in each file the font name had ".ttf.ttf" rather than ".ttf".
=> [galaxie_greek_positional][sil_greek_polytonic]fix font names

release/packages/fv_all/HISTORY.md, release/packages/fv_all/README.md, release/packages/fv_all/build.sh, release/packages/fv_all/source/fv_all.kps.in, release/packages/fv_all/source/readme.htm
We were checking out the associated languages for the fv_all keyboard package, and noticed the build scripts are pulling the last associated language *Zapotec (Latin)* for the sil_euro_latin keyboard. This tweaks the fv_all build script to use *English*.
This is for integrating dictionary support in the First Voices apps in the upcoming month.
Note, the build script is also generating a lot of warnings about the current language tags being valid, but not canonical. 
Per @mcdurdin, we'll address those at another time.
Tagging @madebybridget
=> [fv_all] Associate sil_euro_latin with English

release/x/xinaliq/HISTORY.md, release/x/xinaliq/README.md, release/x/xinaliq/source/help/xinaliq.php, release/x/xinaliq/source/welcome/welcome.htm, release/x/xinaliq/source/xinaliq.keyman-touch-layout, release/x/xinaliq/source/xinaliq.kmn, release/x/xinaliq/source/xinaliq.kps, release/x/xinaliq/xinaliq.keyboard_info, release/x/xinaliq/xinaliq.kpj
Fixes #1696
* Add s-cedilla to the <kbd>s</kbd> key rota
* (edited) Remove circumflex ss per review comment
* Remove stray `q` longpress keys on the <kbd>Shift</kbd> button in the default layer of the touch layout
* Use canonical tag `kjj` instead of `kjj-Latn`
* Fix formatting on welcome page
@KenK-3-21 - Can you clarify if "brother" is spelled with the composing circumflex before "ss"?
=> [xinaliq] Add s-cedilla

release/p/postmodern_english_us_natural/postmodern_english_us_natural.keyboard_info
The PME US Natural keyboard's keyboard info was previously just "Postmodern English US Natural" on the Keyman download page. We've updated it to be more informative.
=> Changed the keyboard info description for PME US Natural to be more informative

release/k/khmer_angkor/HISTORY.md, release/k/khmer_angkor/LICENSE.md, release/k/khmer_angkor/README.md, release/k/khmer_angkor/khmer_angkor.kpj, release/k/khmer_angkor/source/khmer_angkor.kmn, release/k/khmer_angkor/source/khmer_angkor.kps
<kbd>b</kbd><kbd>/</kbd><kbd>I</kbd> incorrectly outputs ប៉ី​ instead of ប៊ី. This is now fixed. The Triisap stays as it is when explicitly typed so.
=> [khmer_angkor] fix BA issue with 17BB-like glyph

release/p/postmodern_english_us_dualstroke/HISTORY.md, release/p/postmodern_english_us_dualstroke/postmodern_english_us_dualstroke.keyboard_info, release/p/postmodern_english_us_dualstroke/postmodern_english_us_dualstroke.kpj, release/p/postmodern_english_us_dualstroke/source/postmodern_english_us_dualstroke.kmn, release/p/postmodern_english_us_dualstroke/source/postmodern_english_us_dualstroke.kps
This change is to align the keyboards with the new lexical model.
=> Changed the BCP 47 code to en-QP for Postmodern English US DualStroke Keyboard

release/p/postmodern_english_uk_natural/postmodern_english_uk_natural.keyboard_info, release/p/postmodern_english_uk_natural/postmodern_english_uk_natural.kpj, release/p/postmodern_english_uk_natural/source/postmodern_english_uk_natural.kmn, release/p/postmodern_english_uk_natural/source/postmodern_english_uk_natural.kps
This change is to align they keyboard language code to the new lexical model.
=> Changed the Postmodern English UK Natural Keyboard BCP 47 tag to en-QP

release/p/postmodern_english_us_natural/postmodern_english_us_natural.keyboard_info, release/p/postmodern_english_us_natural/postmodern_english_us_natural.kpj, release/p/postmodern_english_us_natural/source/postmodern_english_us_natural.kmn, release/p/postmodern_english_us_natural/source/postmodern_english_us_natural.kps
This change is to correlate this keyboard with the new Postmodern lexical model.
=> Changed the Postmodern English US Natural Keyboard BCP 47 tag to en-QP

release/x/xinaliq/HISTORY.md, release/x/xinaliq/LICENSE.md, release/x/xinaliq/README.md, release/x/xinaliq/source/help/xinaliq.php, release/x/xinaliq/source/welcome/welcome.htm, release/x/xinaliq/source/xinaliq.kmn
Follow-on to #1698
During testing of keymanapp/keyman#6477, @bharanidharanj noted that the rota for <kbd>c</kbd> didn't match the help documentation. (The rota reverts to "c" after 5x).
Per the keyboard source, there is no c-cedilla on the rota:
https://github.com/keymanapp/keyboards/blob/e60d8fa3fd599a7c34bcac3d327ff9006a086cd5/release/x/xinaliq/source/xinaliq.kmn#L168-L171
This bumps the keyboard version and fixes the help documentation.
=> [xinaliq] Fix help documentation for "c" key

release/d/dagbani/HISTORY.md, release/d/dagbani/LICENSE.md, release/d/dagbani/README.md, release/d/dagbani/source/dagbani.kmn, release/d/dagbani/source/dagbani.kps, release/d/dagbani/source/readme.htm, release/d/dagbani/source/welcome.htm
The upcoming kmcmp.exe release will generate warnings about inconsistent matches needing NCAPS (https://github.com/keymanapp/keyman/pull/6347)
```
```
=> [dagbani] Add NCAPS  modifier to some rules

release/sil/sil_cameroon_azerty/HISTORY.md, release/sil/sil_cameroon_azerty/source/help/sil_cameroon_azerty.php, release/sil/sil_cameroon_azerty/source/sil_cameroon_azerty.kmn, release/sil/sil_cameroon_azerty/source/sil_cameroon_azerty.kps, release/sil/sil_cameroon_azerty/source/welcome/welcome.htm
The upcoming kmcmp.exe release will generate warnings about inconsistent matches needing NCAPS (https://github.com/keymanapp/keyman/pull/6347)
```
```
=> [sil_cameroon_azerty] Add NCAPS to some rules

release/c/cabecar/HISTORY.md, release/c/cabecar/LICENSE.md, release/c/cabecar/README.md, release/c/cabecar/source/cabecar.kmn, release/c/cabecar/source/cabecar.kps
The upcoming kmcmp.exe release will generate warnings about inconsistent matches needing NCAPS (https://github.com/keymanapp/keyman/pull/6347)
```
```
=> [cabecar] Add NCAPS to some rules

release/basic/basic_kbdyba/HISTORY.md, release/basic/basic_kbdyba/LICENSE.md, release/basic/basic_kbdyba/README.md, release/basic/basic_kbdyba/source/basic_kbdyba.kmn, release/basic/basic_kbdyba/source/basic_kbdyba.kps, release/basic/basic_kbdyba/source/readme.htm
The upcoming kmcmp.exe release will generate warnings about inconsistent matches needing NCAPS (https://github.com/keymanapp/keyman/pull/6347)
```
```
=> [basic_kbdyba] Add NCAPS to some rules

release/b/balochi_latin/HISTORY.md, release/b/balochi_latin/LICENSE.md, release/b/balochi_latin/source/balochi_latin.kmn, release/b/balochi_latin/source/balochi_latin.kps, release/b/balochi_latin/source/readme.htm
Prep for the upcoming Keyman 15 release 
The upcoming kmcmp.exe release will generate warnings about inconsistent matches needing NCAPS (keymanapp/keyman#6347)
```
```
Applies to ll 16-21
=> [balochi_latin] Add NCAPS modifier to avoid inconsistent matches

release/u/ukwuani/HISTORY.md, release/u/ukwuani/README.md, release/u/ukwuani/source/ukwuani.kmn, release/u/ukwuani/source/ukwuani.kps
* Remove extraneous group(main) since it's already on l.14
=> [ukwuani] Remove extraneous group(main)

experimental/t/taigi_poj/HISTORY.md, experimental/t/taigi_poj/LICENSE.md, experimental/t/taigi_poj/README.md, experimental/t/taigi_poj/source/readme.htm, experimental/t/taigi_poj/source/taigi_poj.kmn, experimental/t/taigi_poj/source/taigi_poj.kps, experimental/t/taigi_poj/source/welcome.htm
In prep for upcoming Keyman 15.0 release, this adds NCAPS modifier to some rules to avoid inconsistent matches
=> [taigi_poj] Add NCAPS modifier to some rules

release/fv/fv_tsilhqotin/HISTORY.md, release/fv/fv_tsilhqotin/LICENSE.md, release/fv/fv_tsilhqotin/README.md, release/fv/fv_tsilhqotin/source/fv_tsilhqotin.kmn, release/fv/fv_tsilhqotin/source/fv_tsilhqotin.kps
* Remove duplicate punctuation block
=> [fv_tsilhqotin] Add NCAPS modifier to some rules

build.sh, ci.sh, release/packages/fv_all/build.sh, resources/compile.sh, resources/download-compiler.sh, resources/regression-build.sh, resources/zip.inc.sh, tools/regression.sh
This is part of a larger set of PRs coming which will automate the build of keyboards during the Keyman Developer build.
Adds scripts to do a full build of .kmx and .js files with a specific version of the compiler. Puts results into `output/<version>/` so that we can easily run diff scripts against different versions.
Will first be used in the Keyman Developer CI build, which will download latest version of compiler in the same tier, as well as using the build within the Keyman Developer `developer/release/<version>` folder, which should make for reasonably straightforward comparisons.
If the kmcomp.zip archive includes kmdecomp.exe, the script can also decompile the .kmx keyboards back to .kmn, again in the `output/<version>/` folder, so that we can do textual comparisons of the …
=> feat: regression builds 🚦

.gitignore, build.sh, ci.sh, release/packages/fv_all/build.sh, resources/compile.sh, resources/download-compiler.sh, resources/environment.sh, resources/regression-build.sh, resources/util.sh, resources/zip.inc.sh, tools/regression.sh
This is part of a larger set of PRs coming which will automate the build of keyboards during the Keyman Developer build.
Refactors and rearranges various parts of build scripts:
* Moves functions to search for kmcomp, etc to environment.sh -- this way we can use the search functions from any script
* Moves parse_args from util.sh back to build.sh -- parse_args is specific to build.sh so should not be in a shared util script
* Moves kmcomp downloaded files to tools/kmcomp/ and cleans up older compiler files in tools/ -- this makes it much easier to cut and shut new versions of kmcomp
* Adds color flags to build.sh and related scripts for controlling color output in logs
* Cleans up some mess from .gitignore and ensures that kmcomp and future regression outputs will be ignored.
Note: …
=> chore: cleanup build scripts 🚦

ci.sh
After enabling `set -u` a missing parameter for rsync upload was encountered. This fixes that.
=> fix: add false parameter for rsync

release/sil/sil_jarai/sil_jarai.keyboard_info
The .keyboard.info file requires a font reference for the OSK presented in the sil_jarai's help page to be shown correctly without any dotted circles.
It's to resolve this issue.
=> add font ref to .keyboard.info

release/p/pid_piaroa/HISTORY.md, release/p/pid_piaroa/LICENSE.md, release/p/pid_piaroa/README.md, release/p/pid_piaroa/pid_piaroa.kpj, release/p/pid_piaroa/source/help/pid_piaroa.php, release/p/pid_piaroa/source/pid_piaroa.kmn, release/p/pid_piaroa/source/pid_piaroa.kps, release/p/pid_piaroa/source/readme.htm, release/p/pid_piaroa/source/welcome.htm
This updates the Piaroa keyboard to be able to type ü̧ and Ü̧  — a convention used by at least one community in Colombia.
To type ü̧, press <kbd>AltGr</kbd> + <kbd>u</kbd>, then press <kbd>AltGr</kbd> + <kbd>,</kbd>.
**NOTE**: I do not currently have access to a machine with Windows, so **I did not use Keyman Developer**, and was unable to test on Windows; I developed on my Mac, and used wine to run `kmcomp.x64.exe` to build and test the keyboard. I observed that I **could not use `[RALT]`** on my UK/Ireland Macbook keyboard, so while testing, I used ordinary `[ALT]`, then switched to `[RALT]` when committing the files.
Please let me know if I've missed anything!
**EDIT**: I have also added ñ/Ñ, also based on community requests!
=> [pid_piaroa] add ü̧/Ü̧ to keyboard

release/e/ekwtamil99uni/source/help/srii/tamil_srii.php
Fixing reference found from CI link checker
The relative path to `keyboard_ekwunitamil` help documentation would be `ekwunitamil`.
However, that keyboard is deprecated by thamizha_anjal_paangu
No change to keyboard or the legacy keyboard docs (see keymanapp/help.keyman.com@84372a78a60cad26947f853290c6a01f76bef728)
=> [ekwtamil99uni] docs: Replace keyboard_ekwunitamil link

release/a/armenian_mnemonic/armenian_mnemonic.kpj, release/a/armenian_mnemonic/source/armenian_mnemonic.kmn, release/a/armenian_mnemonic/source/options.htm
In Linux Mint 21 the **Options** screen of the *Armenian Mnemonic* keyboard failed to render because of an incorrect tag pair and escaping ampersand symbol in the `<script>` tag.
=> [armenian_mnemonic] Fixed Options rendering in Linux

release/sil/sil_boonkit/HISTORY.md, release/sil/sil_boonkit/README.md, release/sil/sil_boonkit/sil_boonkit.kpj, release/sil/sil_boonkit/source/sil_boonkit.kmn
The Boonkit currently uses ` as the key to change a consonant into a subjoined consonant by inserting a U+1A60 sakot before it. Unfortunately, most Thai users have the ` and ~ wired to switch keyboards. Changing this behaviour involves a lot of detailed magical clicking and could be considered a regression for the user.
This change adds the same ` subjoining behaviour to the \ key, which previously output (. Notice that there is no corresponding key that outputs ) on the keyboard, thus making the \ somewhat useless. Seems like a perfect compromise. The existing behaviour of ` is left unchanged for backward compatibility.
Warning. This change has not been tested (even syntactically).
=> Refactor boonkit to allow \ as same as ` key

release/gff/gff_amharic/source/help/gff_amharic.php
This update addresses a few issues with the help documentation:
- Tablet layer name fixed, old name `non-amharic` changed to correct new name `amharic-extra`
- Link to related keyboard "Setbat Bet" changed to "Gurage"
- Links to new keyboards added: Harege Fidelat and Mesobe Fidelat
=> Help Documentation Fix: GFF Amharic

release/gff/gff_mesobe_fidelat/HISTORY.md, release/gff/gff_mesobe_fidelat/README.md, release/gff/gff_mesobe_fidelat/gff_mesobe_fidelat.kpj, release/gff/gff_mesobe_fidelat/source/gff_mesobe_fidelat.kmn, release/gff/gff_mesobe_fidelat/source/help/gff_mesobe_fidelat.php
This is a very minor update that changes the "ፀ" key on the "ፀ-layer" from the "Deadkey" type to the "Default" type.
=> GFF Mesobe Fidelat v1.01

release/gff/gff_amharic/source/help/gff_amharic.php, release/gff/gff_mesobe_fidelat/source/help/gff_mesobe_fidelat.php
* gff_mesobe_fidelat: Stray markdown code replaced with HTML tags
* gff_amharic: CSS `code` style definition added to synch with Harege and Mesobe documentation.
=> GFF Documentation Fixes

release/k/karakalpak_latin/source/karakalpak_latin.kmn, release/rac/rac_torwali/source/rac_torwali.kmn, release/sil/sil_yi/source/sil_yi.kmn
From keymanapp/keyman#7583, the upcoming kmcomp 16.0 will flag keyboards that have duplicated `begin` statements.
No functional changes so I'm not bumping any keyboard versions.
=> chore: Remove extraneous begin statements

release/gff/gff_harege_fidelat/gff_harege_fidelat.keyboard_info, release/gff/gff_harege_fidelat/source/help/gff_harege_fidelat.php, release/gff/gff_mesobe_fidelat/gff_mesobe_fidelat.keyboard_info, release/gff/gff_mesobe_fidelat/source/help/gff_mesobe_fidelat.php
These are updates to the `.keyboard_info` files to Harege Fidelat and Mesobe Fidelat to avoid appearing as Keyman Web options.
Paragraph justification is added to the respective `.php` help pages where it was missing.
These updates are as per the recommendations in the Keyman Community form discussions here:  https://community.software.sil.org/t/question-on-keyman-web-the-kmd-web-target/6972/1
=> GFF Harege Fidelat & Mesobe Fidelat Adjustments for Keyman Web

release/gff/gff_amh_7/gff_amh_7.keyboard_info, release/gff/gff_amharic/gff_amharic.keyboard_info, release/gff/gff_amharic_classic/gff_amharic_classic.keyboard_info, release/gff/gff_blin/gff_blin.keyboard_info, release/gff/gff_geez/gff_geez.keyboard_info, release/gff/gff_gurage/gff_gurage.keyboard_info, release/gff/gff_gurage_legacy/gff_gurage_legacy.keyboard_info, release/gff/gff_tigrinya_eritrea/gff_tigrinya_eritrea.keyboard_info, release/gff/gff_tigrinya_ethiopia/gff_tigrinya_ethiopia.keyboard_info
This PR changes all references to the Wookianos (and other) web fonts referenced in the `.keyboard_info` files of the GFF keyboards.  The `fonts` field entry was also added to a number of keyboards that did not have it set.  An exception is the gff_ethiopic_7 (language-neutral) keyboard where a correct update would need more time and so will be revisited later.
The formatting of the `.keyboard_info` files was also synchronized.
This PR should complete #2072
=> Migration to the Noto Ethiopic Web Fonts.

release/sil/sil_boonkit/README.md
This change updates the README.md file for sil_boonkit so that it lists Linux as supported platform.
The keyboard already supports Linux, but the readme didn't reflect that until now.
=> [sil_boonkit] Update README.md

release/m/malar_malayalam/HISTORY.md, release/m/malar_malayalam/README.md, release/m/malar_malayalam/malar_malayalam.kpj, release/m/malar_malayalam/source/malar_malayalam.keyman-touch-layout, release/m/malar_malayalam/source/malar_malayalam.kmn, release/m/malar_malayalam/source/malar_malayalam.kps
* Fix `ntha` keystroke to get conjunct `n̪t̪a` `<0D28, 0D4D, 0D24>`.
* Add shift modifier to `caps` (shift lock) layer in touch layout. (double-tapping Shift to reach a 'sticky' Caps Lock layer)
=> [malar_malayalam] Update to version 1.6

release/packages/fv_all/HISTORY.md, release/packages/fv_all/LICENSE.md, release/packages/fv_all/README.md, release/packages/fv_all/build.sh, release/packages/fv_all/source/fv_all.kps.in, release/packages/fv_all/source/readme.htm
Fixes #2143
> We may need to fixup fv_all/build.sh to read from the .kmp files.
I elected to update build.sh to use jq to parse the compiled `.keyboard_info` files to determine the updated keyboard versions for all the keyboards included in fv_all.kmp.
Also bumped the version of fv_all to 12.5.
Tagging @caforbes
=> [fv_all] - Use jq to determine included keyboard versions

release/packages/fv_all/build.sh, tools/jq.inc.sh
Addresses review comments from #2173 
* Use jq.inc.sh for cross-platform build
* Remove unnecessary assignments and logging
Not bumping fv_all version since no new functionality
=> [fv_all] Cleanup build.sh

ci.sh, resources/help-keyman-com.sh, tools/regression.sh
Addresses https://github.com/keymanapp/keyboards/pull/2180#pullrequestreview-1377011619
> A follow-up could update all other JQ references in ci.sh, help-keyman-com.sh, regression.sh scripts so that we can run keyboard builds on all CI agents.
Note, I only updated the include of jq.inc.sh, and intentionally am not refactoring all the `KEYBOARDROOT` defines with builder script.
Later on, we might also need to check other CI requirements like 7z.
=> chore: Standardize usage of jq.inc.sh

release/gff/gff_harari/source/help/gff_harari.php
Follow-on to #2196 and #2201
Attempting to fix broken help links at
https://help.keyman.com/keyboard/gff_harari/1.0/gff_harari flagged by keymanapp/help.keyman.com#655
No keyboard change so leaving version intact.
=> [gff_harari] Fix image links for help

release/n/nepali_traditional/HISTORY.md, release/n/nepali_traditional/LICENSE.md, release/n/nepali_traditional/README.md, release/n/nepali_traditional/nepali_traditional.kpj, release/n/nepali_traditional/source/nepali_traditional.kmn
in nepali text, RRA (ऱ) is always followed by halanta ( ् ) for eyelash half RA as in (पऱ्यो) , hence adding RRA halanta instead of RRA only
=> nepali_traditional add eyelash half RA in desktop layout

release/gff/gff_geez/HISTORY.md, release/gff/gff_geez/README.md, release/gff/gff_geez/gff_geez.keyboard_info, release/gff/gff_geez/gff_geez.kpj, release/gff/gff_geez/source/gff_geez.kmn, release/gff/gff_geez/source/gff_geez.kps, release/gff/gff_geez/source/help/gff_geez.php, release/gff/gff_geez/source/welcome.htm
This version of the keyboard removes the `gff_geez.js` file from the packaging to avoid the listings of available mobile layouts.  Documentation has also been enhanced to provide a link to the language-neutral keyboard.
=> GFF Geʾez Keyboard v2.0.1

release/b/balochi_scientific/HISTORY.md, release/b/balochi_scientific/LICENSE.md, release/b/balochi_scientific/balochi_scientific.kpj, release/b/balochi_scientific/source/balochi_scientific.kmn, release/b/balochi_scientific/source/balochi_scientific.kps, release/l/lao_phonetic/HISTORY.md, release/l/lao_phonetic/LICENSE.md, release/l/lao_phonetic/README.md, release/l/lao_phonetic/lao_phonetic.kpj, release/l/lao_phonetic/source/help/lao_phonetic.php, release/l/lao_phonetic/source/lao_phonetic.kmn, release/l/lao_phonetic/source/lao_phonetic.kps, release/l/lao_phonetic/source/readme.htm, release/l/lao_phonetic/source/welcome.htm, release/packages/gff_gurage_and_amharic/HISTORY.md, release/packages/gff_gurage_and_amharic/README.md, release/packages/gff_gurage_and_amharic/gff_gurage_and_amharic.kpj, release/packages/gff_gurage_and_amharic/source/gff_gurage_and_amharic.kps
Partially addresses #2303 
@mcdurdin I did not address:
```
gff_amh_7.kps
gff_amh_powerpack_7.kps
gff_ethiopic_7.kps
```
because those are deprecated. 
How do you want that handled? Or maybe you should not be testing deprecated keyboards?
=> [2303_missing_js] Update some of the keyboards in this issue

release/itrans/itrans_roman/source/help/itrans_roman.php, release/m/mon_phonetic/source/help/mon_phonetic.php, release/sil/sil_tchad/source/help/sil_tchad.php, release/u/uma_graphic/source/help/uma_graphic.php, release/u/uma_phonetic/source/help/uma_phonetic.php, release/u/urdu_phonetic/source/help/urdu_phonetic.php
=> [php_shorten_again] Missed a few

experimental/gff/gff_geez_emufi/source/help/gff_geez_emufi.php
This update corrects a path for an image that appears broken online.  Since the update is to the non-packaged PHP help file, I'm hoping the update can be made without the version bump.
=> GFF Ge'ez Manuscript Keyboard - PHP Image Path Fix

release/sil/sil_euro_latin/HISTORY.md, release/sil/sil_euro_latin/LICENSE.md, release/sil/sil_euro_latin/source/sil_euro_latin.keyman-touch-layout, release/sil/sil_euro_latin/source/sil_euro_latin.kmn
Fixes #2375 
On the shift layer, longpress on the comma <kbd>,</kbd> was outputting `<` because the KeymanWeb engine processes the keystroke as <kbd>shift</kbd>+<kbd>,</kbd>.
Converting from K_COMMA to U_002C should fix this.
=> chore: Fix longpress commas on touch layout

release/t/tai_tham_my/source/help/tai_tham_my.php
The font doesn't seem to display in the help page. The font doesn't seem to have a bit set for the Tai Tham script so this is an experiment to see if specifying the font in a span will force it to display the glyphs.
=> [tai_tham_php] Experiment to see if font will display

resources/help-keyman-com.sh
Per https://build.palaso.org/buildConfiguration/Keyboards_Upload/417714?buildTab=log&focusLine=26382&linesState=25980&logView=flowAware, the build failed due to:
```
05:55:14   Committing and pushing updated keyboard documentation (if any)
05:55:14   ensuring master is up to date
05:55:15   From https://github.com/keymanapp/help.keyman.com
05:55:15    * branch              master     -> FETCH_HEAD
05:55:15      6cc08de9..51fbc572  master     -> origin/master
05:55:18   error: The following untracked working tree files would be overwritten by merge:
05:55:18     keyboard/fv_nuucaanul/9.1.4/Nuucaanul.png
05:55:18     keyboard/fv_nuucaanul/9.1.4/fv_nuucaanul.php
05:55:18   Please move or remove them before you merge.
05:55:18   Updating 6cc08de9..51fbc572
05:55:18   Aborting
05:55:18 …
```
=> chore: ensure master up to date earlier when deploying help

resources/s-keyman-com.sh
Fixes #2323.
All fonts in release/shared/fonts will be deployed to s.keyman.com.
Furthermore, changes to s.keyman.com will now be opened as a pull request, in order to allow us to manually address any CI failures, and remove the need for direct commits to master.
Note: a further improvement in the future may be to scan all packages for web font references and include those.
Note: another question is about font versioning -- if a font is updated, s.keyman.com will continue to serve the old one for some time due to caching. How important is this to fix?
=> feat: automatically deploy fonts to s.keyman.com

release/gff/gff_tigre/gff_tigre.kpj, release/gff/gff_tigrinya_eritrea/HISTORY.md, release/gff/gff_tigrinya_eritrea/README.md, release/gff/gff_tigrinya_eritrea/gff_tigrinya_eritrea.kpj, release/gff/gff_tigrinya_eritrea/source/gff_tigrinya_eritrea.kmn, release/gff/gff_tigrinya_eritrea/source/gff_tigrinya_eritrea.kps
This update removes the "EthiopicUnicodeNormal.ttf" and "EthiopicUnicodeItalic.ttf"  fonts which have an unknown license.  Aside from the version number, no other changes occur.
=> GFF Eritrean Tigrinya Keyboard v2.0.2

release/gff/gff_tigre/HISTORY.md, release/gff/gff_tigre/README.md, release/gff/gff_tigre/gff_tigre.kpj, release/gff/gff_tigre/source/gff_tigre.kmn, release/gff/gff_tigre/source/gff_tigre.kps
This update removes the "EthiopicUnicodeNormal.ttf" and "EthiopicUnicodeItalic.ttf"  fonts which have an unknown license.  Aside from the version number, no other changes occur.
=> GFF Tigre Keyboard v1.0.2

release/gff/gff_tigrinya_ethiopia/HISTORY.md, release/gff/gff_tigrinya_ethiopia/README.md, release/gff/gff_tigrinya_ethiopia/gff_tigrinya_ethiopia.kpj, release/gff/gff_tigrinya_ethiopia/source/gff_tigrinya_ethiopia.kmn, release/gff/gff_tigrinya_ethiopia/source/gff_tigrinya_ethiopia.kps
This update removes the "EthiopicUnicodeNormal.ttf" and "EthiopicUnicodeItalic.ttf"  fonts which have an unknown license.  Aside from the version number, no other changes occur.
=> GFF Ethiopian Tigrinya Keyboard v2.0.3

release/n/newa_traditional_extended/HISTORY.md, release/n/newa_traditional_extended/newa_traditional_extended.kpj, release/n/newa_traditional_extended/source/newa_traditional_extended.kmn, release/n/newa_traditional_extended/source/newa_traditional_extended.kps, release/n/newa_traditional_extended/source/newa_traditional_extended.kvks
Show texts for the invisible character keys i.e. zwnj, zwj and dead keys on OSK, which were missing in the previous version.
=> [newa_traditional_extended] show texts for the invisible character keys on OSK

legacy/c/cs-pinyin/cs-pinyin.keyboard_info
Fixes #2494 
Since this keyboard is in `legacy` we aren't updating the keyboard package itself, just the target to Windows only.
=> [cs-pinyin] Remove macos from target list

release/i/idc_deseret/source/help/idc_deseret.php
I approved the `idc_deseret` keyboard without an online help file.
=> [idc_help] add help file for idc_deseret

release/k/khmer_angkor/HISTORY.md, release/k/khmer_angkor/source/khmer_angkor.keyman-touch-layout, release/k/khmer_angkor/source/khmer_angkor.kmn
Fixes #2221 by adding 17.0 non-printing glyphs  (see keymanapp/keyman#9846) to the khmer_angkor spacebar.
Default spacebar outputs ZWSP (text `*ZWSp*`)
shift-spacebar outputs U+0020  (text `*Sp*`)
Because the spacebar typically shows the keyboard name, only the longpress glyph is really visible
Note: first commit is just differences from Keyman Developer 17.0 beta.
Can jump to ll. 1441, 1447,  and 1901.
=> [khmer_angkor] Add non-printing characters to spacebar

release/rac/rac_dogri/source/rac_dogri.kps
I was trying out the kmc compiler on staging-17.0 branch and had to replace a lot of slashes in .kps files to build on Linux.
That revealed the pathing in rac_dogri.kps can be simplified.
Not bumping versions since no rebuild necessary.
=> [rac_dogri] chore: Simplify pathing in rac_dogri.kps

release/fv/fv_hailzaqvla/HISTORY.md, release/fv/fv_hailzaqvla/fv_hailzaqvla.kpj, release/fv/fv_hailzaqvla/source/fv_hailzaqvla.kmn, release/fv/fv_hailzaqvla/source/fv_hailzaqvla.kps, release/fv/fv_hailzaqvla/source/fv_hailzaqvla.kvks, release/fv/fv_hailzaqvla/source/help/fv_hailzaqvla.php, release/fv/fv_hailzaqvla/source/welcome.htm
Added left/right alt distinction and updated on-screen keyboard to correct issue with on-screen keyboard not showing option layer correctly on Mac.
=> [fv_hailzaqvla] patch to on-screen keyboard

release/sil/sil_tanguat/sil_tanguat.keyboard_info, release/sil/sil_tanguat/sil_tanguat.kpj, release/sil/sil_tanguat/source/sil_tanguat.kps
Follow-on to #2625 which failed to deploy because the .keyboard_info file was missing. Also because kmcomp in the CI build doesn't handle .kpj 2.0 format.
* Downgrade .kpj format to 1.0
* Add .keyboard_info file for keyboard deployment
=> [sil_tanguat] Build for 16.0

release/packages/fv_all/HISTORY.md, release/packages/fv_all/LICENSE.md, release/packages/fv_all/README.md, release/packages/fv_all/source/fv_all.kps.in, release/packages/fv_all/source/readme.htm
Addresses the first part of #2675 
> * fv_all kps version in the [source file](https://github.com/keymanapp/keyboards/blob/02603516ed2382d610d5571a0cd2dbdd3fa4d416/release/packages/fv_all/source/fv_all.kps.in#L21)
Changes:
* Increments fv_all package so rebuilding fv_all will add fv_sguuxs (from #2648)
* Update copyright dates
=> [fv_all] - Add fv_sguuxs

release/a/ausephon/LICENSE.md
The date in the LICENSE.md copyright statement should be the range 2023-2024 (after the update in PR #2705 ).
Since this file is not included in the keyboard package, there's no need to update any version number information.
=> [ausephon] Update LICENSE.md

legacy/d/devu-mikes/source/help/devu-mikes.php, release/gff/gff_awngi_xamtanga/source/help/gff_awngi_xamtanga.php, release/gff/gff_gurage_legacy/source/help/gff_gurage_legacy.php, release/sil/sil_nko/source/help/sil_nko.php
Relates to keymanapp/help.keyman.com#1209
where @mcdurdin said
> The correct fix is to take the HTML entities out of the $pagetitle in the affected pages in keyboards.
This updates the current help pages for:
* devu-mikes
* gff_awngi_xamtanga
* gff_gurage_legacy
* sil_nko
=> fix special chars in keyboard help page names/titles

release/fv/fv_nlakapamuxcheen/source/help/fv_nlakapamuxcheen.php, release/fv/fv_nlakapamuxcheen/source/welcome/welcome.htm
Follow-on to #2731 in fixing broken link in the help files.
Intentionally not bumping the keyboard version.
=> [fv_nlakapamuxcheen] Fix broken link in help

release/fv/fv_henqeminem/HISTORY.md, release/fv/fv_henqeminem/fv_henqeminem.kpj, release/fv/fv_henqeminem/source/fv_henqeminem.keyman-touch-layout, release/fv/fv_henqeminem/source/fv_henqeminem.kmn
MOBILE - added colon, moved middle dot to longpress. GENERAL - added a rule for backspacing vowels with acute accent
=> fv_henqeminem - minor changes

release/fv/fv_nlakapamuxcheen/HISTORY.md, release/fv/fv_nlakapamuxcheen/README.md, release/fv/fv_nlakapamuxcheen/fv_nlakapamuxcheen.keyboard_info, release/fv/fv_nlakapamuxcheen/fv_nlakapamuxcheen.kpj, release/fv/fv_nlakapamuxcheen/source/fv_nlakapamuxcheen.kmn, release/fv/fv_nlakapamuxcheen/source/fv_nlakapamuxcheen.kps
Second attempt to remove "fv_" from keyboard name on the Keyman page. I believe the change made in the .kps and .kpj should fix that!
=> [fv nlakapamuxcheen] Second attempt at correcting name

release/packages/fv_all/HISTORY.md, release/packages/fv_all/build.sh, release/packages/fv_all/keyboards.csv, release/packages/fv_all/source/fv_all.kps.in
Relates to Keyman 18.0 work for keymanapp/keyman#2036
This brings in [keyboards.csv](https://github.com/keymanapp/keyman/blob/master/oem/firstvoices/keyboards.csv) file to the keyboards repro for FV to maintain and includes it in the fv_all.kmp package.
Changes to keyboards.csv
* Streamline columns to ID, Region
* fv_all/build.sh script overrides name and language info for basic_kbdcan and sil_euro_latin
Also bumps fv_all version to 12.10.
Note, the fv_all.kps.in template is still for the kmcomp 16.0 compiler.
TODO to migrate it to staging-17.0 format.
=> [fv_all] Add keyboards.csv to fv_all.kmp package

release/fv/fv_gitsenimx/source/help/fv_gitsenimx.php, release/fv/fv_gitsenimx/source/welcome/welcome.htm
Fixes help deployment fail on [keymanapp/help.keyman.com#2100](https://github.com/keymanapp/help.keyman.com/actions/runs/9119237009/job/25074170077)
The png filename is **fv_gitsenimx_U_.png**
No version update since this is just help documentation.
=> [fv_gitsenimx] Fix help links to png file

build.sh, package-lock.json, package.json
Also moves to npm ci instead of npm install for consistent versioning
=> chore: upgrade to kmc 17.0.326

ci.sh
After merging staging-17.0, found that ci.sh still had references to old include scripts.
=> fix: remove codesign.sh and fix util.inc.sh reference in ci.sh

docs/custom-build-script.md, resources/help-keyman-com.sh, resources/util.inc.sh
These were removed as part of the builder script implementation of build.sh in the staging-17.0 branch, but I neglected to check other usages. Safer to put them back (copied out of util.sh pre-merge), and then we can tidily remove them again in the future.
=> fix: restore color variables and die() function to util.inc.sh

release/o/obolo_chwerty/source/help/obolo_chwerty.php
Reverts the png references that were changed in #2804.
Since the png filenames stayed the same in welcome.htm, I elected to use the original filenames.
To fix the failing help deployment on keymanapp/help.keyman.com#1305
=> [obolo_chwerty] Revert png filenames in help

resources/build_targets.inc.sh, tools/regression.sh
Relates to keymanapp/keyman#11811.
Build script would fail if `-k release/packages/fv_all` were the only command line parameters, as `grep` would return an error while preparing the list of files to build.
=> fix: support build of just fv_all from build.sh

release/sil/sil_ethiopic_power_g/HISTORY.md, release/sil/sil_ethiopic_power_g/LICENSE.md, release/sil/sil_ethiopic_power_g/sil_ethiopic_power_g.kpj, release/sil/sil_ethiopic_power_g/source/sil_ethiopic_power_g.kmn, release/sil/sil_ethiopic_power_g/source/sil_ethiopic_power_g.kps, release/sil/sil_ethiopic_power_g/source/sil_ethiopic_power_g.kvks
Minor revisions to the SIL Ethiopic Power-G keyboard to include an on-screen keyboard and the inclusion of the Abyssinica SIL font in the distribution.
* On-Screen keyboard added.
* AbyssinicalSIL-Regular.ttf added to package.
* Upgrade project to Keyman Developer 17.0 format.
=> [SIL Ethiopic Power-G] Add On-Screen keyboard in v1.2.4

release/s/sgaw_karen/source/help/sgaw_karen.php
Follows #2832 to fix help deployment current failing on keymanapp/help.keyman.com#1328
=> [sgaw_karen]: Fix single quote in help page name

release/template/README.md
These template files may no longer be used, but this updates them to match Keyman v17 expectations.
=> [template] update template files

release/packages/fv_all/HISTORY.md, release/packages/fv_all/keyboards.csv, release/packages/fv_all/source/fv_all.kps.in
Adds new keyboards fv_ojibwa_rdot (#2849) and fv_severn_ojibwa_rdot (#2851) to fv_all.kmp.
* Also added the 2 keyboards + regions to `keyboards.csv` (not currently used, but eventually will be used when the FV app gets moved from the main repo)
TODO: Update keyboards.csv in the main repo which is still being actively used to build the mobile apps.
=> [fv_all] Add fv_ojibwa_rdot and fv_severn_ojibwa_rdot

release/k/kaithi_inscript/HISTORY.md, release/k/kaithi_inscript/LICENSE.md, release/k/kaithi_inscript/source/kaithi_inscript.kmn
LICENSE had the wrong copyright. Since it is now included in the Keyman package I decided the keyboard version needed bumping.
=> [kaithi_inscript] Correct copyright in LICENSE.md

release/t/taigi_viet_telex/source/help/taigi_viet_telex.php
The information from the welcome.htm was copied to the taigi_viet_telex.php file, so that the online help will have the same information as the help packaged with the keyboard.
=> [taigi_viet_telex] update PHP help file from welcome.htm

release/f/foochow/source/foochow.kps
See also https://github.com/keymanapp/keyman/issues/12193
=> chore(foochow): restore missing FollowKeyboardVersion tag

release/c/cs_pinyin/source/cs_pinyin.kps, release/o/obolo_chwerty/source/obolo_chwerty.kps, release/s/sgaw_karen/source/sgaw_karen.kps, release/s/sharada_inscript/source/sharada_inscript.kps, release/v/vithkuqi/source/vithkuqi.kps
These changes do not require version bumps because at present the Description field is used only by the website.
Relates-to: keymanapp/keyman#12202
=> chore: add missing keyboard descriptions

release/packages/fv_all/HISTORY.md, release/packages/fv_all/source/fv_all.kps.in
This is a major bump of fv_all.kmp to 13.0 which incorporates all of the FirstVoices keyboard updates up to July 31, 2024.
Note: does not include #3011
=> [fv_all] Update package version to 13.0

release/i/imperial_aramaic/HISTORY.md, release/i/imperial_aramaic/source/imperial_aramaic.xml
Resolves an issue with the visual keyboard by using updated kmc 17.0.330 compiler.
=> chore: re-release Imperial Aramaic 1.0.1

release/e/ekwtamil99uni/source/ekwtamil99uni.kps, release/y/yidgha/source/yidgha.kps
I noticed two keyboard pages listed `null` for the Description
https://keyman.com/keyboards/ekwtamil99uni
https://keyman.com/keyboards/yidgha
This adds descriptions to the .kps files (from the help.keyman.com Overview content)
Not bumping keyboard versions
=> [ekwtamil99uni, yidgha] Fill in blank descriptions

package-lock.json, package.json
This has been tested in #3143 -- the fix has addressed the build failure there, so this should be good to go. Relevant fixes in this build:
* keymanapp/keyman#12609
* keymanapp/keyman#12628
=> chore: upgrade to kmc 17.0.332

release/basic/basic_kbdolch/HISTORY.md, release/basic/basic_kbdolch/LICENSE.md, release/basic/basic_kbdolch/source/basic_kbdolch.kmn
Corrected whitespace error in symbols_key store of `basic_kbdolch`
Line 122 of basic_kbdolch.kmn contains `[SHIFTK_K]`, which should not compile, and would emit an ERROR_InvalidToken once [#12604](https://github.com/keymanapp/keyman/pull/12604) is merged.
Corrected to `[SHIFT K_K]` , keyboard version increased to 1.0.1, and `HISTORY.md` updated.
=> Correct whitespace error in symbols_key store for basic_kbdolch

release/sil/sil_el_ethiopian_latin/HISTORY.md, release/sil/sil_el_ethiopian_latin/source/sil_el_ethiopian_latin.kmn, release/sil/sil_el_ethiopian_latin/source/sil_el_ethiopian_latin.kps
Addresses 1 kbd in https://github.com/keymanapp/keyboards/issues/3221
Note that the messages about script `'Zyyy'` did not make sense to me. I just reviewed the language tags to make sure they were correct and fixed the ones that were not.
=> [sil_el_ethiopian_latin] Update language tags

release/d/dakota_smsc/source/help/dakota_smsc.php
Help file doesn't display. `<style>` doesn't have and end.
Also removed some of the keyboard installation instructions since those aren't recommended to include. The online help for Keyman will always be the most up-to-date.
=> [dakota_smsc] Fix help file

release/sil/sil_nubian/HISTORY.md, release/sil/sil_nubian/LICENSE.md, release/sil/sil_nubian/source/help/sil_nubian.php, release/sil/sil_nubian/source/readme.htm, release/sil/sil_nubian/source/sil_nubian.kmn, release/sil/sil_nubian/source/sil_nubian.kps, release/sil/sil_nubian/source/welcome/welcome.htm
Fixes #3290 
Fixes the link to Sophia Nubian fonts in the help docs to `https://software.sil.org/sophianubian`
=> [sil_nubian] Fix link to Sophia Nubian font in help docs

legacy/t/tengwar/tengwar.keyboard_info
The patch in #3336 missed a comma, which broke the release build. (The files in legacy/ are more fragile and do not have many build checks, as they generally do not get modified.)
Fixes: #3333
Emerging-From: #3336
=> fix: add missing comma in tengwar.keyboard_info

experimental/k/khmer_ldml/source/khmer_ldml.xml
Should not need a new version of the keyboard, just to pass Keyman Developer 18.0 checks.
=> fix(khmer_ldml): encoding of `<` should be `&lt;`

experimental/l/luo_lakeside/source/help/luo_lakeside.php
Failed [deployment](https://github.com/keymanapp/help.keyman.com/actions/runs/14002922828/job/39212520637):
```
PHP Parse error:  syntax error, unexpected identifier "Lakeside" in ./keyboard/luo_lakeside/1.0/luo_lakeside.php on line 2
```
=> chore: fix typo in luo_lakeside.php

release/fv/fv_hailzaqvla/source/help/fv_hailzaqvla.php
Fixes: HELP-KEYMAN-COM-DPE
Error
> Keyboard Keyboard_fv_hailzaqvla does not have a layer with id alt
Update the osk layers to use `rightalt` and `rightalt-shift`
No change in version since this is only updating the online help file.
=> [fv_hailzaqvla] Fix layers in online help

experimental/u/unifon/source/help/unifon.php
Fixes: HELP-KEYMAN-COM-DDZ
Error:
>Keyboard Keyboard_unifon does not have a layer with id numeric
Removes invalid layers in the online help file.
No version change since only updating online help
=> [unifon] Fix missing layers in online help

release/b/belgian_typewriter/source/help/belgian_typewriter.php
Fixes error about missing layer `symbol`
Online help updated to use `rightalt`
=> [belgian_typewriter]: Fix missing layer in online help

release/sil/sil_tepehuan/source/help/sil_tepehuan.php
Fixes the failed keyboard help deployment on https://github.com/keymanapp/help.keyman.com/actions/runs/14653975660/job/41125613577
> PHP Parse error:  Invalid indentation - tabs and spaces cannot be mixed in ./keyboard/sil_tepehuan/1.1/sil_tepehuan.php on line 28
Screenshot of the key sequences
Fixes: keymanapp/keyman#13756
=> [sil_tepehuan] Fix whitespace in help file

release/sil/sil_tai_dam_typewriter/source/help/sil_tai_dam_typewriter.php
Similar to #3458 which fixed deployment of php help file to help.keyman.com
Fixed invalid mix of tab/whitespace in the heredoc CSS syntax.
I had to consolidate the font line here. 
@mcdurdin - is that valid syntax?
=> [sil_tai_dam_typewriter] Fix whitespace in help file

release/gff/gff_amharic/source/help/html.css
I noticed in the PHP help file that the tables looked broken, they were missing some CSS definitions that were not copied over from the `welcome.htm` .  This update adds the missing CSS to the `html.css` file that the PHP file imports.
Since this is only an update to the online help, it should not impact the keyboard version.
=> [gff_amharic] GFF Amharic - Adding Missing CSS Styles for PHP Help Page

release/d/dazaga_gourane_karra/HISTORY.md, release/d/dazaga_gourane_karra/README.md, release/d/dazaga_gourane_karra/source/dazaga_gourane_karra.kmn, release/d/dazaga_gourane_karra/source/dazaga_gourane_karra.kps
The keyboard page on keyman has the wrong title, because the name tag in the .kps file still had the old name.
=> [dazaga_gourane_karra] Correct wrong keyboard name

release/l/lavanya/HISTORY.md, release/l/lavanya/README.md, release/l/lavanya/source/lavanya.kmn, release/l/lavanya/source/lavanya.kps, release/l/lavanya/source/readme.htm
1. Updated backspace handling. When using backspace (for example, after typing k+i, if you press backspace on i, it shows క instead of క్). This has been fixed. Now inherent vowel in not maintained even when the backspace is used. 
2. There are better touch layout for phones. Gboard stands out for Telugu. Rather than pushing for an inferior tool, I've decided to remove support touch layout.
=> [lavanya] Updated backspace handling. Removed support for touch layout

release/sil/sil_greek_polytonic/HISTORY.md, release/sil/sil_greek_polytonic/source/sil_greek_polytonic.keyman-touch-layout, release/sil/sil_greek_polytonic/source/sil_greek_polytonic.kmn
Some longpress keys for vowels (both upper and lower case) had a blank "text" field or the "text" field was missing entirely. This seemed to work in some circumstances (that is, the character was displayed based on the U_xxxx id value), but failed on iOS.
In some cases the base key was repeated as a longpress key. When I noticed that, I deleted the duplication (since there are so many longpress keys on most vowels).
In addition, fixed a bug in the .kmn file, prompted by a compiler warning. Line 640 was:
```
any(upVRo)           + any(K_Del) > index(upV,2)                c <A  + *  A
```
and produced a warning:
"sil_greek_polytonic.kmn:641 - hint KM020B0: The store referenced in index() is longer than the store referenced in any()"
store(upVRo) has seven elements, store(K_Del) has one, …
=> [sil_greek_polytonic] fix longpress keys

experimental/h/hindi_flick/HISTORY.md, experimental/h/hindi_flick/source/hindi_flick.kmn
Adds a workaround for start of line handling to resolve a compatibility issue with Firefox rich text controls.
Relates-to: keymanapp/keyman#14148
=> fix(hindi_flick): start of line handling
