bj_cree_east/build.cmd, bj_oji_cree/build.cmd, gff_amh_7/source/gff-amh-7.kmn, gff_ethiopic_7/source/gff-ethiopic-7.kmn
Works around broken build for bj_ keyboards with a temporary fix. So leave #45 open for now as we should address the root cause in future. The other fixes are fine -- just updating deprecated code style.
=> #45 and other source tweaks so build of all keyboards completes without failing

release/el/el_dinka/source/el_dinka.kps
=> Fix author email

legacy/gff/gff-amh-powerpack-7/gff-amh-powerpack-7.keyboard_info, legacy/h/hieroglyphic/hieroglyphic.keyboard_info, legacy/s/sabdalipi assamese/sabdalipi assamese.keyboard_info, legacy/t/tir-er-uni/tir-er-uni.keyboard_info, legacy/t/tir-et-uni/tir-et-uni.keyboard_info, legacy/t/tunisianspokenarabic/tunisianspokenarabic.keyboard_info, release/packages/gff_amh_powerpack_7/gff_amh_powerpack_7.keyboard_info, tools/keyboard_info.source.json
This updates the .keyboard_info schema and fixes a handful of keyboard_infos that don't meet the new spec
=> Enforce language array uniqueness in keyboard_info

release/rac/rac_gawar_bati/rac_gawar_bati.keyboard_info
=> [rac_gawar_bati] add example to rac_gawar_bati.keyboard_info

release/template/README.md, release/template/template.keyboard_info
The README.md and template.keyboard_info have been updated per David's proposal.
=> template: update two files per David's proposal

release/l/lazuri/README.md, release/l/lazuri/lazuri.keyboard_info, release/l/lazuri/source/welcome/welcome.htm
=> [lazuri] Add -Latn to BCP 47 code in README.md and .keyboard_info files

release/b/balochi_scientific/balochi_scientific.keyboard_info, release/b/balochi_scientific/source/welcome/welcome.htm
=> [balochi_scientific] update language tags in .keyboard_info file

release/sil/sil_el_ethiopian_latin/sil_el_ethiopian_latin.keyboard_info
=> [sil_el_ethiopian_latin] update description

release/gff/gff_tigrinya_ethiopia/source/help/gff_tigrinya_ethiopia.php
Added help file based on welcome.htm
=> [gff_tigrinya_ethiopia] added help file

resources/util.sh
=> Ensure that when the build aborts, it has a non-zero error code.

build.sh, resources/compile.sh
This PR goes along with keymanapp/keyboards-starter#4
=> Support keyboards-starter repo with build script

release/sil/sil_boonkit/HISTORY.md, release/sil/sil_boonkit/README.md, release/sil/sil_boonkit/sil_boonkit.kpj, release/sil/sil_boonkit/source/help/sil_boonkit.php, release/sil/sil_boonkit/source/sil_boonkit.kmn, release/sil/sil_boonkit/source/sil_boonkit.kps, release/sil/sil_boonkit/source/welcome/welcome.htm
=> [sil_boonkit] correct case in filename references

legacy/g/grkpoly2/grkpoly2.keyboard_info
=> [grkpoly2] put Greek (el) first in language list

legacy/b/basiclao/basiclao.keyboard_info, legacy/c/camazert/camazert.keyboard_info, legacy/c/cameroon qwerty non-u kbd-fonts/cameroon qwerty non-u kbd-fonts.keyboard_info, legacy/e/enhlao/enhlao.keyboard_info, legacy/i/icetot/icetot.keyboard_info, legacy/i/ipa93_km5/ipa93_km5.keyboard_info, legacy/i/ipatep/ipatep.keyboard_info, legacy/k/keymancolombia/keymancolombia.keyboard_info, legacy/k/keymanguahibo/keymanguahibo.keyboard_info, legacy/m/malta/malta.keyboard_info, legacy/m/mohawk_u/mohawk_u.keyboard_info, legacy/s/sanskrit csx/sanskrit csx.keyboard_info, legacy/t/tsciianjal/tsciianjal.keyboard_info, legacy/w/winmacdene/winmacdene.keyboard_info, legacy/y/yorubaok/yorubaok.keyboard_info
* I updated the keyboard_info file to indicate these ANSI keyboards are obsolete. If a Unicode keyboard is available, I gave a suggested alternate URL.
* Despite Mohawk having Unicode in the name @mcdurdin assures us it is ANSI.
=> [ansi_obsolete_new] Obsolete ANSI keyboards

release/rac/rac_balti/source/help/rac_balti.php, release/rac/rac_brahui/source/help/rac_brahui.php, release/rac/rac_dameli/source/help/rac_dameli.php, release/rac/rac_khowar/source/help/rac_khowar.php
* ```<body>``` tag needed removing. On Opera, Edge and Chrome the page was getting cropped. 
* Khowar keyboard name needed updating.
=> [rac-help] Remove body tag to fix cropped images

release/o/osage_nation/osage_nation.keyboard_info
A further attempt to force mobile to use the font.
=> [osage_nation] add font information to keyboard_info

release/sil/sil_tchad/HISTORY.md, release/sil/sil_tchad/README.md, release/sil/sil_tchad/sil_tchad.kpj, release/sil/sil_tchad/source/sil_tchad.keyman-touch-layout, release/sil/sil_tchad/source/sil_tchad.kmn
Switched to Tahoma in hopes that the chi will have better support. Added keys to touch layout.
=> [sil_tchad] Updated mobile layout

release/g/galaxie_greek_mnemonic/source/help/galaxie_greek_mnemonic.php, release/g/galaxie_hebrew_mnemonic/source/help/galaxie_hebrew_mnemonic.php
=> [galaxie_*_mnemonic] Fix to tab toggle in php files for mnemonic keybooards

release/rac/rac_yidgha/source/help/rac_yidgha.php
Help file was not in correct format
=> [rac_yidgha] Turn help file into php header format

release/sil/sil_indic_roman/source/help/sil_indic_roman.php
help file had question marks for some characters.
=> [sil_indic_roman] fix help file

release/fv/fv_diitiidatx/README.md, release/fv/fv_gwichin/README.md, release/fv/fv_nuucaanul/README.md, release/fv/fv_stlatlimxec/README.md, release/fv/fv_uwikala/README.md
I added "Todo" about canonical ordering. These are ones I already merged. I'll try to catch the remaining ones as I merge them.
=> [fv_todo] Added canonical order todo item

release/rac/rac_yidgha/rac_yidgha.keyboard_info, release/sil/sil_yi/README.md
These are two fixes @darcywong00 asked me to do back in September.
=> [sil_yi and rac_yidgha] modified per request

release/fv/fv_denesuline_epsilon/README.md, release/fv/fv_gwichin/README.md
=> [fv_normalize] add message about need for normalizing

release/rac/rac_aer/HISTORY.md, release/rac/rac_aer/README.md, release/rac/rac_aer/rac_aer.keyboard_info, release/rac/rac_aer/rac_aer.kpj, release/rac/rac_aer/source/help/rac_aer.php, release/rac/rac_aer/source/rac_aer.keyman-touch-layout, release/rac/rac_aer/source/rac_aer.kmn, release/rac/rac_aer/source/rac_aer.kps
=> [rac_aer] update version and font info and fix up various layout issues

release/gff/gff_amharic/gff_amharic.keyboard_info
Resetting lastModifiedDate under @LornaSIL 's recommendation: https://github.com/keymanapp/keyboards/pull/556#issuecomment-444532426
=> gff_amharic v1.7: Setting lastModifiedDate to commit time.

release/h/hieroglyphic/hieroglyphic.keyboard_info
=> [hieroglyphic] Add legacyId to keyboard_info

release/rac/rac_pashto/source/help/rac_pashto.php, release/rac/rac_uyghur/README.md, release/rac/rac_uyghur/source/help/rac_uyghur.php
* help files were not displaying layouts. I think they needed to be in a container
* home link for Uyghur was wrong
No changes were made to keyboard or files used in the package, so I did not bump the version.
=> [rac_uyghur][rac_pashto] fixing up help file and home link

release/rac/rac_pashto/source/help/rac_pashto.php, release/rac/rac_uyghur/source/help/rac_uyghur.php
I finally understood what @darcywong00 was telling me.
=> [rac_help_ug_ps2] Change symbol to shift

release/rac/rac_pashai/source/help/rac_pashai.php
I didn't get the right syntax for the help file and the osk layout is not displaying properly.
=> [rac_pashai-help] Fix help osk layout

release/fv/fv_cree_latin/fv_cree_latin.kpj, release/fv/fv_cree_latin/source/fv_cree_latin.kps
I selected followkeyboardversion flag, but I didn't bump the version since online it is v1.000 I hope this fixes the issue.
=> [fv_cree_latin] Select followkeyboardversion flag

release/template/HISTORY.md, release/template/LICENSE.md, release/template/README.md, release/template/template.keyboard_info
=> [template] update template files

legacy/g/grkpoly2/grkpoly2.keyboard_info
* Added grc-Grek to list of languages in keyboard_info
* No permission from author to make changes to keyboard itself
Fixes #258
=> [grkpoly2] add grc-Grek to keyboard_info - no change to keyboard itself

release/sil/sil_pan_africa_positional/source/help/sil_pan_africa_positional.php, release/sil/sil_pan_africa_positional/source/welcome/welcome.htm
When working on keyboard test data a few weeks back, I found a few typos in the welcome.htm file (and in the .php help file).
=> [sil_pan_africa_positional] correct typos in welcome.htm

release/sil/sil_pan_africa_positional/HISTORY.md, release/sil/sil_pan_africa_positional/LICENSE.md, release/sil/sil_pan_africa_positional/README.md, release/sil/sil_pan_africa_positional/sil_pan_africa_positional.kpj, release/sil/sil_pan_africa_positional/source/sil_pan_africa_positional.kmn, release/sil/sil_pan_africa_positional/source/sil_pan_africa_positional.kps
Change version number from 1.1 to 1.1.1 so changes made in #764 will be propagated.
=> [sil_pan_africa_positional] update version number

release/fv/fv_northern_tutchone/HISTORY.md, release/fv/fv_northern_tutchone/README.md, release/fv/fv_northern_tutchone/source/fv_northern_tutchone.kmn, release/fv/fv_northern_tutchone/source/fv_northern_tutchone.kvks
=> [fv_northern_tutchone] fix canonical ordering for U+0328

release/fv/fv_tagizi_dene/HISTORY.md, release/fv/fv_tagizi_dene/README.md, release/fv/fv_tagizi_dene/source/fv_tagizi_dene.kmn, release/fv/fv_tagizi_dene/source/fv_tagizi_dene.kvks
=> [fv_tagizi_dene] fix canonical ordering for U+0328

release/sil/sil_limbu_phonetic/source/help/sil_limbu_phonetic.php
This PR is an experiment. It was created entirely on GitHub.
=> [sil_limbu_phonetic] update osk element in .php file

legacy/k/kyrghyz/DEPRECATED.md, release/basic/basic_kbdkyr/basic_kbdkyr.keyboard_info
This is just deprecating. No version bump needed.
=> [basic_kbdkyr] Deprecate kyrghyz keyboard

release/a/aksarabali_panlex/HISTORY.md, release/a/aksarabali_panlex/README.md, release/a/aksarabali_panlex/source/aksarabali_panlex.kmn
This fixes additional reported issues for inputting syllable coda -r, -ng, and -h after certain vowel characters. Version bumped to 1.0.2.
=> [aksarabali_panlex] additional fixes for coda consonants

release/b/balochi_inpage/balochi_inpage.keyboard_info
I didn't think it necessary to create a new version just for changing the description.
=> [balochi_inpage] Change keyboard_info description

release/i/indigenous_nt/source/help/indigenous_nt-layout.pdf, release/i/indigenous_nt/source/help/indigenous_nt_layout.pdf
Renamed pdf file to match help php reference.
=> Indigenous NT Final

release/i/indigenous_nt/HISTORY.md, release/i/indigenous_nt/README.md, release/i/indigenous_nt/indigenous_nt.kpj, release/i/indigenous_nt/source/help/indigenous_nt.php, release/i/indigenous_nt/source/indigenous_nt.keyman-touch-layout, release/i/indigenous_nt/source/indigenous_nt.kmn, release/i/indigenous_nt/source/indigenous_nt.kps, release/i/indigenous_nt/source/indigenous_nt.kvks, release/i/indigenous_nt/source/readme.htm, release/i/indigenous_nt/source/welcome/welcome.htm
Refined the touch layout to reduce number of keys and increase size of buttons.
=> 3.4 update

release/sil/sil_myanmar_mywinext/README.md
=> [sil_myanmar_mywinext] add TO DO note to README.md

experimental/README.md
new README.md for experimental folder
=> [infrastructure] update README.md

legacy/b/bengali_kab/DEPRECATED.md, legacy/m/malayalam_kab/DEPRECATED.md, release/basic/basic_kbdinbe2/basic_kbdinbe2.keyboard_info, release/m/malar_malayalam_inscript/malar_malayalam_inscript.keyboard_info
=> [inscript-beng-mlym] Deprecate two Inscript keyboards

legacy/g/gujarati_kab/DEPRECATED.md, legacy/p/punjabi_kab/DEPRECATED.md, legacy/t/telegu_kab/DEPRECATED.md, legacy/u/urdu_kab/DEPRECATED.md, release/basic/basic_kbdinguj/basic_kbdinguj.keyboard_info, release/basic/basic_kbdinpun/basic_kbdinpun.keyboard_info, release/basic/basic_kbdintel/basic_kbdintel.keyboard_info, release/basic/basic_kbdurdu/basic_kbdurdu.keyboard_info
=> [kab_guj_pun_tel_urd] Deprecate 4 keyboards

legacy/t/tir-er-uni/DEPRECATED.md, legacy/t/tir-et-uni/DEPRECATED.md, legacy/t/tir_er_uni_ez/DEPRECATED.md, legacy/t/tir_et_uni_ez/DEPRECATED.md, release/gff/gff_tigrinya_eritrea/gff_tigrinya_eritrea.keyboard_info, release/gff/gff_tigrinya_ethiopia/gff_tigrinya_ethiopia.keyboard_info
=> [deprecate_tir] Deprecate 4 keyboards with author permission

legacy/t/tamil99m/DEPRECATED.md, release/basic/basic_kbdtam99/basic_kbdtam99.keyboard_info
Deprecating one keyboard.
No version bump needed.
=> [deprecate_tamil99m] deprecate mobile layout

release/nrc/nrc_crk_cans/HISTORY.md, release/nrc/nrc_crk_cans/README.md, release/nrc/nrc_crk_cans/nrc_crk_cans.kpj, release/nrc/nrc_crk_cans/source/help/nrc_crk_cans.php, release/nrc/nrc_crk_cans/source/nrc_crk_cans.keyman-touch-layout, release/nrc/nrc_crk_cans/source/nrc_crk_cans.kmn, release/nrc/nrc_crk_cans/source/nrc_crk_cans.kps, release/nrc/nrc_crk_cans/source/welcome/welcome.htm
* Fixed some issues with backspace key layer switching
* Fixed some typos in the documentation
=> [nrc_crk_cans] 1.0.1

release/e/easy_chakma/easy_chakma.keyboard_info
Fixes #999
Depends on keymanapp/s.keyman.com#9
=> [easy_chakma] Add RibengUni font to keyboard_info

legacy/gff/gff-gez-powerpack-7/DEPRECATED.md
=> [gff-gez-powerpack-7] This keyboard was not actually deprecated

release/b/burushaski_girminas/source/help/burushaski_girminas.php
Add help file for keyboard I approved.
=> [burushaski_girminas_php] Add help file

release/s/saraiki/HISTORY.md, release/s/saraiki/source/saraiki.kmn, release/s/saraiki/source/saraiki.kvks
Follow-on to #1057 
This should address issues found on https://keymanweb.com/#skr-arab,Keyboard_saraiki
=> [saraiki] Fix RTL and distinguish left/right ctrl-alt on OSK

release/s/saraiki/source/saraiki.kmn
=> [saraiki] Bump version to 1.1

release/basic/README.md
Someone wanted to add a keyboard to basic_kbdus and I realized we needed to document how this folder is used.
=> [basic_readme] Added README.md to basic folder

release/basic/basic_kbdfar/README.md, release/basic/basic_kbdogham/README.md, release/basic/basic_kbdoldit/README.md, release/basic/basic_kbdosm/README.md, release/basic/basic_kbdrum/README.md
Closes #865 and #866.
These can be fixed when the keyboard needs more work.
=> [basic_todo] Documents things to do for these keyboards

experimental/t/taigi_poj/HISTORY.md, experimental/t/taigi_poj/README.md, experimental/t/taigi_poj/source/help/taigi_poj.php, experimental/t/taigi_poj/source/readme.htm, experimental/t/taigi_poj/source/taigi_poj.kmn, experimental/t/taigi_poj/source/taigi_poj.kps, experimental/t/taigi_poj/source/welcome.htm, experimental/t/taigi_poj/taigi_poj.keyboard_info, experimental/t/taigi_poj/taigi_poj.kpj
Added missing images describe here: https://github.com/keymanapp/keyboards/pull/1087#issuecomment-592598219
=> taigi_poj keyboard v1.1

release/gff/gff_geez/HISTORY.md, release/gff/gff_geez/LICENSE.md, release/gff/gff_geez/README.md, release/gff/gff_geez/gff_geez.kpj, release/gff/gff_geez/source/gff_geez.kmn, release/gff/gff_geez/source/gff_geez.kps
Allow continuation of western numerals after the first entry.
=> GFF Ge'ez v1.5

experimental/fv/fv_haisla/source/help/fv_haisla.php
I actually tested that the link works this time.
=> [fv_haisla_help2] Haisla help file take 2

release/packages/fv_all/HISTORY.md, release/packages/fv_all/LICENSE.md, release/packages/fv_all/README.md, release/packages/fv_all/fv_all.kpj, release/packages/fv_all/source/fv_all.kps.in, release/packages/fv_all/source/readme.htm
@mcdurdin can you review my changes?
@madebybridget please watch so you know what kinds of changes need to be made in the future.
=> [fv_all] Update FV package to include fv_haisla

legacy/b/burmese02/DEPRECATED.md, release/sil/sil_myanmar_my3/sil_myanmar_my3.keyboard_info
Deprecating Burmese02 keyboard per author.
=> [burmese02] Deprecate keyboard per author

release/packages/fv_all/HISTORY.md, release/packages/fv_all/README.md, release/packages/fv_all/source/fv_all.kps.in
#1152 didn't update the version in fv_all.kps.in so it didn't get built.
Also added DejaVuSans.ttf shared font to go with sil_euro_latin
=> [fv-all] Version bump to trigger build of fv_all.kmp

legacy/x/xaadkil/DEPRECATED.md, release/fv/fv_hlgaagilda_xaayda_kil/fv_hlgaagilda_xaayda_kil.keyboard_info
=> [fv_dep] Deprecate xaadkil keyboard

release/basic/basic_kbdus/HISTORY.md, release/basic/basic_kbdus/LICENSE.md, release/basic/basic_kbdus/README.md, release/basic/basic_kbdus/basic_kbdus.kpj, release/basic/basic_kbdus/source/basic_kbdus.keyman-touch-layout, release/basic/basic_kbdus/source/basic_kbdus.kmn, release/basic/basic_kbdus/source/basic_kbdus.kps, release/basic/basic_kbdus/source/help/basic_kbdus.php, release/basic/basic_kbdus/source/readme.htm, release/basic/basic_kbdus/source/welcome/welcome.htm
Adds a phone layout.
Incorporates many of the changes requested in PR #1078 
Closes #1078
=> [basic_kbdus] US Basic keyboard - add a phone layout

release/s/soqotri_arabic/HISTORY.md, release/s/soqotri_arabic/LICENSE.md, release/s/soqotri_arabic/README.md, release/s/soqotri_arabic/soqotri_arabic.kpj, release/s/soqotri_arabic/source/soqotri_arabic.keyman-touch-layout, release/s/soqotri_arabic/source/soqotri_arabic.kmn, release/s/soqotri_arabic/source/soqotri_arabic.kps
=> [soqotri_arabic] Enhancement to access shift layer of mobile layout

release/o/obolo_chwerty/source/help/obolo_chwerty.php
Add help file based on author's welcome.htm file.
=> [obolo_chwerty_php] Add help file for keyboard

release/packages/vm_tamil/HISTORY.md, release/packages/vm_tamil/README.md, release/packages/vm_tamil/source/vm_tamil.kps, release/packages/vm_tamil/vm_tamil.kpj
Hopefully addresses Issue #1215 
Sorry I'm so dense. I've done the packages so infrequently that I forgot how to do it.
=> [vm_tamil] Add .kmn files and change location of compiled files

release/fv/fv_kwakwala_liqwala/HISTORY.md, release/fv/fv_kwakwala_liqwala/LICENSE.md, release/fv/fv_kwakwala_liqwala/README.md, release/fv/fv_kwakwala_liqwala/fv_kwakwala_liqwala.kpj, release/fv/fv_kwakwala_liqwala/source/fv_kwakwala_liqwala.keyman-touch-layout, release/fv/fv_kwakwala_liqwala/source/fv_kwakwala_liqwala.kmn, release/fv/fv_kwakwala_liqwala/source/fv_kwakwala_liqwala.kps, release/fv/fv_kwakwala_liqwala/source/fv_kwakwala_liqwala_kmw_help.htm, release/fv/fv_kwakwala_liqwala/source/welcome/welcome.htm
Relates to #1246 
Relates to #1237
@madebybridget do you want to check this first?
=> [fv_kwakwala_liqwala] Revert mobile layout and fix headers on htm files

legacy/gff/gff_sgw_7/DEPRECATED.md, release/gff/gff_gurage/HISTORY.md, release/gff/gff_gurage/README.md, release/gff/gff_gurage/gff_gurage.keyboard_info, release/gff/gff_gurage/gff_gurage.kpj, release/gff/gff_gurage/source/gff_gurage.kmn
Added mapping to save a step: <KA'IB> + T_HAMIS > <ZEMEDE:HAMIS>
=> GFF Gurage 0.7 Beta 3

legacy/h/helabasauni/HISTORY.md, legacy/h/helabasauni/LICENSE.md, legacy/h/helabasauni/README.md, legacy/h/helabasauni/helabasauni.keyboard_info, legacy/h/helabasauni/helabasauni.kpj, legacy/h/helabasauni/source/helabasauni.kps, legacy/h/helabasauni/source/readme.htm
Relates to #337 
The source we have is for the custom-encoded keyboard. We do not have source for the Unicode keyboard.
Thus, I'm just moving the .js file into a .kmp.
* I added a readme.htm
* I included the chart.pdf for documentation.
=> [helabasauni] Move js file into a kmp

release/q/qom/source/help/qom.php
I neglected to check the help file when I approved the keyboard.
=> [qom] Fix help file

release/s/sxava/source/help/sxava.php
I didn't ask the author of this keyboard to make a help file.
=> [sxava] Add help file

release/sil/sil_ipa/HISTORY.md, release/sil/sil_ipa/README.md, release/sil/sil_ipa/sil_ipa.kpj, release/sil/sil_ipa/source/help/sil_ipa.php, release/sil/sil_ipa/source/sil_ipa.kmn, release/sil/sil_ipa/source/sil_ipa.kps, release/sil/sil_ipa/source/welcome/welcome.htm
=> [sil_ipa] Update documentation on Africanist upstep and downstep

release/t/tawallammat_latin/HISTORY.md, release/t/tawallammat_latin/README.md, release/t/tawallammat_latin/source/help/tawallammat_latin.php, release/t/tawallammat_latin/source/readme.htm, release/t/tawallammat_latin/source/tawallammat_latin.kmn, release/t/tawallammat_latin/source/welcome/welcome.htm, release/t/tawallammat_latin/tawallammat_latin.kpj
A contributor to this keyboard is recognized and added to the matadata of this keyboard.
=> [tawallammat_latin] Update metadata

release/sil/sil_ipa/HISTORY.md, release/sil/sil_ipa/README.md, release/sil/sil_ipa/source/help/sil_ipa.php, release/sil/sil_ipa/source/sil_ipa.kmn, release/sil/sil_ipa/source/welcome/welcome.htm
=> [sil_ipa] Documentation fixes, no behavior changes

experimental/w/wancho/source/help/wancho.php, release/s/sahaptin_yakima/sahaptin_yakima.keyboard_info, release/s/sahaptin_yakima/source/help/sahaptin_yakima.php
Add help for sahaptin_yakima.
Fix language tag for sahaptin_yakima.keyboard_info file.
Also remove extra h1 header from wancho.php help file.
=> Fix yakima

legacy/gff/gff_tir_er_7/source/help/gff_tir_er_7.php, legacy/gff/gff_tir_et_7/source/help/gff_tir_et_7.php, legacy/i/indic roman transliteration/source/help/indic roman transliteration.php, legacy/k/khowar/source/help/khowar.php, legacy/t/tamil - visual media/source/help/keyboardchart-modular.htm, legacy/t/tamil - visual media/source/help/keyboardchart-typewriter.htm, legacy/t/thamizha anjal/source/help/keyboardchart.htm, legacy/t/thamizha bamini/source/help/keyboardchart.htm, legacy/t/thamizha typewriter/source/help/keyboardchart.htm, release/basic/basic_kbdinben/source/help/chart.php, release/g/galaxie_greek_mnemonic/source/help/galaxie_greek_mnemonic.php, release/g/galaxie_greek_mnemonic/source/help/keyboardchart.php, release/g/galaxie_greek_positional/source/help/galaxie_greek_positional.php, release/g/galaxie_greek_positional/source/help/keyboardchart.php, release/t/thamizha_anjal_paangu/source/help/thamizha_anjal_paangu.php, release/t/tibetan_direct_input/source/help/tibetan_direct_input.php
Relates to keymanapp/help.keyman.com#233.
PR keymanapp/help.keyman.com#237 contains the same fixes, in order to verify prior to commit here. It also fixes older versions of docs that would not be updated by the keyboard documentation push. I will revalidate to ensure I haven't missed anything once this merges.
=> fix: broken links

release/sil/sil_hmd_plrd/HISTORY.md, release/sil/sil_hmd_plrd/LICENSE.md, release/sil/sil_hmd_plrd/README.md, release/sil/sil_hmd_plrd/sil_hmd_plrd.keyboard_info, release/sil/sil_hmd_plrd/sil_hmd_plrd.kpj, release/sil/sil_hmd_plrd/source/help/sil_hmd_plrd.php, release/sil/sil_hmd_plrd/source/readme.htm, release/sil/sil_hmd_plrd/source/sil_hmd_plrd.kmn, release/sil/sil_hmd_plrd/source/sil_hmd_plrd.kps, release/sil/sil_hmd_plrd/source/sil_hmd_plrd.kvks, release/sil/sil_hmd_plrd/source/welcome/welcome.htm
=> [sil_hmd_plrd] Add fonts to Ahmao (SIL) keyboard package

legacy/g/grkpoly2/source/help/grkpoly2.php
=> [grkpoly2] Update documentation regarding accessing AltGr

release/c/clavbur9/HISTORY.md, release/c/clavbur9/README.md, release/c/clavbur9/clavbur9.keyboard_info, release/c/clavbur9/clavbur9.kpj, release/c/clavbur9/source/clavbur9.kmn, release/c/clavbur9/source/clavbur9.kps
=> [clavbur9] Add a new language to keyboard and bump version

release/shared/fonts/sil/scheherazade_new/FONTLOG.txt, release/shared/fonts/sil/scheherazade_new/OFL-FAQ.txt, release/shared/fonts/sil/scheherazade_new/OFL.txt, release/shared/fonts/sil/scheherazade_new/ScheherazadeNew_README.txt
We should begin encouraging new or revised keyboards to use **Scheherazade New** instead of **Scheherazade**.
=> [scheherazade_new] Add new version of SIL font to shared repo

legacy/isis/isis_gujarati/source/help/isis_gujarati.php, legacy/isis/isis_gurmukhi/source/help/isis_gurmukhi.php, legacy/isis/isis_kannada/source/help/isis_kannada.php, legacy/isis/isis_oriya/source/help/isis_oriya.php, legacy/isis/isis_telugu/source/help/isis_telugu.php
isisinfo.php is not present, so this generates warnings on the site. Not needed.
=> chore: cleanup old isis php files

release/gff/gff_gurage_legacy/README.md, release/gff/gff_gurage_legacy/gff_gurage_legacy.kpj, release/gff/gff_gurage_legacy/source/gff_gurage_legacy.kmn, release/gff/gff_gurage_legacy/source/gff_gurage_legacy.kps, release/gff/gff_gurage_legacy/source/help/gff_gurage_legacy.php, release/gff/gff_gurage_legacy/source/welcome.htm
Reset language ID to sgw-Ethi-XL to synch with https://github.com/keymanapp/lexical-models/pull/105 and avoid the issue reported in https://github.com/keymanapp/keyman/issues/3806 .
=> GFF Gurage Legacy Keyboard v0.11

legacy/b/bukawa/source/help/bukawa.php, legacy/h/harlatn/source/help/harlatn.php, legacy/i/inuktitut_4/source/help/inuktitut_4.php, legacy/k/km_cree/source/help/km_cree.php, legacy/k/km_ojibwasyllabics/source/help/km_ojibwasyllabics.php, legacy/k/km_ojicreesyllabics/source/help/km_ojicreesyllabics.php, legacy/k/kmhmu/source/help/kmhmu.php, legacy/k/korda/source/help/korda.php, legacy/k/korean_morse/source/help/korean_morse.php, legacy/l/laounicodebasic_on_thaikbd/source/help/laounicodebasic_on_thaikbd.php, legacy/t/thompsonu/source/help/thompsonu.php, legacy/t/turkmen/source/help/turkmen.php, release/rac/rac_kashmiri/source/help/rac_kashmiri.php, release/sil/sil_korean_morse/source/help/sil_korean_morse.php
These changes do not require a version bump. This is just cleanup of malformed PHP files as found when I was preparing an update to help.keyman.com.
=> chore: cleanup php headers

release/bj/bj_cree_east_latn/source/help/bj_cree_east_latn.php, release/bj/bj_cree_west_latn/source/help/bj_cree_west_latn.php
Phone layout was not displaying.
=> [bj_help] Syntax for mobile layout fixed

legacy/a/armenian/armenian.keyboard_info, legacy/isis/isis_bangla/isis_bangla.keyboard_info, legacy/isis/isis_devanagari/isis_devanagari.keyboard_info, legacy/isis/isis_gujarati/isis_gujarati.keyboard_info, legacy/isis/isis_gurmukhi/isis_gurmukhi.keyboard_info, legacy/m/mbsindhi/mbsindhi.keyboard_info
=> [1398_desktop] Change support from mobile to just desktop

release/bj/bj_innu_phonemic/source/help/bj_innu_phonemic.php
Help file still had an htm header.
=> [bj_innu_phonemic] Fix help header

release/gff/gff_amharic_classic/source/help/gff_amharic_classic.php
Corrections to the data-states attributes to list the keyboard layers correctly.
Addresses remarks from: https://github.com/keymanapp/keyboards/pull/1423#issuecomment-749740572
=> GFF Amharic Classic Help File Fixes

release/sil/sil_hmd_plrd/sil_hmd_plrd.keyboard_info, release/sil/sil_lpo_plrd/sil_lpo_plrd.keyboard_info, release/sil/sil_ygp_plrd/sil_ygp_plrd.keyboard_info, release/sil/sil_ygp_plrd/source/help/sil_ygp_plrd.php, release/sil/sil_yna_plrd/sil_yna_plrd.keyboard_info, release/sil/sil_ywq_plrd/sil_ywq_plrd.keyboard_info, release/sil/sil_ywq_plrd/source/help/sil_ywq_plrd.php
Accomplishes #1418 (plus handled the other 4 Miao keyboards too).
=> [plrd] Added font info to keyboard_info file

release/sil/sil_sgaw_karen/HISTORY.md, release/sil/sil_sgaw_karen/LICENSE.md, release/sil/sil_sgaw_karen/README.md, release/sil/sil_sgaw_karen/sil_sgaw_karen.kpj, release/sil/sil_sgaw_karen/source/help/sil_sgaw_karen.php, release/sil/sil_sgaw_karen/source/readme.htm, release/sil/sil_sgaw_karen/source/sil_sgaw_karen.kmn, release/sil/sil_sgaw_karen/source/sil_sgaw_karen.kps, release/sil/sil_sgaw_karen/source/welcome/welcome.htm
a few minor updates on help and welcome pages
=> [sil_sgaw_karen] minor updates on help

release/g/galaxie_greek_mnemonic/HISTORY.md, release/g/galaxie_greek_mnemonic/LICENSE.md, release/g/galaxie_greek_mnemonic/README.md, release/g/galaxie_greek_mnemonic/galaxie_greek_mnemonic.kpj, release/g/galaxie_greek_mnemonic/source/galaxie_greek_mnemonic.kmn, release/g/galaxie_greek_mnemonic/source/galaxie_greek_mnemonic.kps, release/g/galaxie_greek_mnemonic/source/help/galaxie_greek_mnemonic.php, release/g/galaxie_greek_mnemonic/source/readme.htm, release/g/galaxie_greek_mnemonic/source/welcome/welcome.htm, release/g/galaxie_hebrew_mnemonic/HISTORY.md, release/g/galaxie_hebrew_mnemonic/LICENSE.md, release/g/galaxie_hebrew_mnemonic/README.md, release/g/galaxie_hebrew_mnemonic/galaxie_hebrew_mnemonic.kpj, release/g/galaxie_hebrew_mnemonic/source/galaxie_hebrew_mnemonic.kmn, release/g/galaxie_hebrew_mnemonic/source/galaxie_hebrew_mnemonic.kps, release/g/galaxie_hebrew_mnemonic/source/readme.htm, release/g/galaxie_hebrew_mnemonic/source/welcome/welcome.htm, release/packages/galaxie_greek_hebrew_mnemonic/HISTORY.md, release/packages/galaxie_greek_hebrew_mnemonic/LICENSE.md, release/packages/galaxie_greek_hebrew_mnemonic/README.md, release/packages/galaxie_greek_hebrew_mnemonic/galaxie_greek_hebrew_mnemonic.keyboard_info, release/packages/galaxie_greek_hebrew_mnemonic/galaxie_greek_hebrew_mnemonic.kpj, release/packages/galaxie_greek_hebrew_mnemonic/source/galaxie_greek_hebrew_mnemonic.kps, release/packages/galaxie_greek_hebrew_mnemonic/source/readme.htm, release/packages/galaxie_greek_hebrew_mnemonic/source/welcome/greek-welcome.htm, release/packages/galaxie_greek_hebrew_mnemonic/source/welcome/hebrew-welcome.htm, release/packages/galaxie_greek_hebrew_mnemonic/source/welcome/welcome.htm
=> [galaxie mnemonic] changes to remove macOS, web, mobile, linux

release/sil/sil_hebrew/HISTORY.md, release/sil/sil_hebrew/README.md, release/sil/sil_hebrew/source/sil_hebrew.kmn, release/sil/sil_hebrew/source/sil_hebrew.kps
I forgot to add the .js to package. :(
=> [sil_hebrew] add .js file to package so it will work on mobile

release/r/rawang/HISTORY.md, release/r/rawang/LICENSE.md, release/r/rawang/README.md, release/r/rawang/rawang.kpj, release/r/rawang/source/help/rawang.php, release/r/rawang/source/rawang.keyman-touch-layout, release/r/rawang/source/rawang.kmn, release/r/rawang/source/rawang.kps, release/r/rawang/source/readme.htm, release/r/rawang/source/welcome/welcome.htm
Closes #1338 
This is just a tablet layout. If a phone layout is required, we'll need to open a new issue/PR.
=> [rawang] Add tablet layout

release/shared/fonts/sil/scheherazade_new/FONTLOG.txt, release/shared/fonts/sil/scheherazade_new/OFL-FAQ.txt, release/shared/fonts/sil/scheherazade_new/OFL.txt
New version of Sch for use in packages.
=> [font_scheherazade] Add new version

release/k/khmer_angkor/HISTORY.md, release/k/khmer_angkor/README.md, release/k/khmer_angkor/khmer_angkor.kpj, release/k/khmer_angkor/source/help/khmer_angkor.php, release/k/khmer_angkor/source/khmer_angkor.kmn, release/k/khmer_angkor/source/khmer_angkor.kps
An image in the welcome and help pages does not show up correctly and this is to fix it.
Should the version number be bumped to 1.0.9?
=> [khmer_angkor] fix the missing image

experimental/t/tangsa_lakhum/source/help/tangsa_lakhum.php, experimental/t/tangsa_lakhum/tangsa_lakhum.keyboard_info
I forgot about the help file and that font info was needed to display this new script.
No version bump needed as this is not part of the package.
=> [tangsa_lakhum] Add font to keyboard_info and help file

release/sil/sil_ipa/HISTORY.md, release/sil/sil_ipa/LICENSE.md, release/sil/sil_ipa/README.md, release/sil/sil_ipa/sil_ipa.kpj, release/sil/sil_ipa/source/help/sil_ipa.php, release/sil/sil_ipa/source/sil_ipa.kmn, release/sil/sil_ipa/source/sil_ipa.kps, release/sil/sil_ipa/source/welcome/welcome.htm
Fixes #1532 
Also attempts to fix help file which is not displaying properly online: https://help.keyman.com/keyboard/sil_ipa/1.8.4/sil_ipa
=> [sil_ipa] Fix conflict with DE hardware keyboard

release/a/aksarabali_panlex/README.md, release/a/aksarabali_panlex/source/help/aksarabali_panlex.php
Fixes #1545 
The fix should be done to welcome.htm as well. I put that in the README.md as a "To Do".
=> [aksarabali_panlex] Update help file to call a Balinese font

release/nrc/nrc_makah/HISTORY.md, release/nrc/nrc_makah/LICENSE.md, release/nrc/nrc_makah/README.md, release/nrc/nrc_makah/nrc_makah.kpj, release/nrc/nrc_makah/source/nrc_makah.kmn, release/nrc/nrc_makah/source/nrc_makah.kps, release/nrc/nrc_makah/source/readme.htm, release/nrc/nrc_makah/source/welcome/welcome.htm
=> [nrc_makah] Add new version of Andika to keyboard

release/sil/sil_bunong/HISTORY.md, release/sil/sil_bunong/README.md, release/sil/sil_bunong/sil_bunong.kpj, release/sil/sil_bunong/source/help/sil_bunong.php, release/sil/sil_bunong/source/sil_bunong.kmn, release/sil/sil_bunong/source/welcome/welcome.htm
Add CSS tabs to the keyboard's welcome page and update the English version of the help page to be consistent with that of the welcome's.
=> [sil_bunong] add translations to welcome page

release/sil/sil_madi/source/help/sil_madi.php
Help page isn't displaying because of a single quote within single quotes.
=> [sil_madi] fix php single quote so it will display

release/sil/sil_madi/source/help/sil_madi.php
I missed the fact that the osk syntax was wrong also.
=> [madi_php] fix layout display on help file

release/basic/basic_kbdwol/source/help/basic_kbdwol.php
Help file has question marks because file structure was ANSI and not utf8.
=> [basic_kbdwol] Change file to utf8 so there are no question marks

README.md
Accidentally deleted in PR #1662
=> [readme_main] Add main README.md file back in

release/o/obolo_chwerty/source/help/obolo_chwerty.php, release/o/obolo_qwerty/source/help/obolo_qwerty.php, release/sil/sil_madi/source/help/sil_madi.php
This only fixes broken links as reported in https://github.com/keymanapp/help.keyman.com/issues/450
I note that the sil_madi help appears to have diverged from the welcome but this PR does not attempt to resolve that.
=> chore: fix broken links

release/k/khmer_angkor/HISTORY.md, release/k/khmer_angkor/README.md, release/k/khmer_angkor/extras/regression_tests/Robat.xml, release/k/khmer_angkor/extras/regression_tests/ស្ប៊ី.xml, release/k/khmer_angkor/extras/regression_tests/ហ្វ៊ី.xml, release/k/khmer_angkor/khmer_angkor.kpj, release/k/khmer_angkor/source/khmer_angkor.kmn
* update rules to account for clusters with HA and exception with BA
* add robat rule
* add regression tests
=> [khmer_angkor] update rules and add regression test

release/sil/sil_myanmar_my3/HISTORY.md, release/sil/sil_myanmar_my3/README.md, release/sil/sil_myanmar_my3/sil_myanmar_my3.kpj, release/sil/sil_myanmar_my3/source/sil_myanmar_my3.keyman-touch-layout, release/sil/sil_myanmar_my3/source/sil_myanmar_my3.kmn
=> [sil_myanmar_my3] Update touch layout

release/g/galaxie_greek_positional/galaxie_greek_positional.keyboard_info, release/sil/sil_greek_polytonic/sil_greek_polytonic.keyboard_info
Fixes #1704 
Also adds a font to the sil_greek_polytonic web keyboard
=> [greek_font] Update font for keyboard_info

release/nlci/nlci_devanagari_winscript/HISTORY.md, release/nlci/nlci_devanagari_winscript/LICENSE.md, release/nlci/nlci_devanagari_winscript/README.md, release/nlci/nlci_devanagari_winscript/nlci_devanagari_winscript.kpj, release/nlci/nlci_devanagari_winscript/source/help/nlci_devanagari_winscript.php, release/nlci/nlci_devanagari_winscript/source/nlci_devanagari_winscript.kmn, release/nlci/nlci_devanagari_winscript/source/nlci_devanagari_winscript.kps, release/nlci/nlci_devanagari_winscript/source/nlci_devanagari_winscript.kvks, release/nlci/nlci_devanagari_winscript/source/readme.htm, release/nlci/nlci_devanagari_winscript/source/welcome/welcome.htm
Replaces PR #1053 
It looks like Issue #751 was handled in Version 2.2 so that Issue can be closed.
=> [nlci_devanagari_winscript] Resubmit PR #1053

release/sil/sil_euro_latin/source/help/sil_euro_latin.php
=> [sil_euro_latin] Update help file to mention longpress keys

release/n/nailangs/HISTORY.md, release/n/nailangs/LICENSE.md, release/n/nailangs/README.md, release/n/nailangs/nailangs.kpj, release/n/nailangs/source/nailangs.kmn, release/n/nailangs/source/nailangs.kps
Per author's request: can you please help change the name of the Nailangs Keyboards' author from Ade Oseni to Adebunmi Adeniran or D. Adebunmi Adeniran as I have changed my surname since 2017 and legally, I should not be using Oseni at all.
=> chore: rename Nailangs author

release/c/chinuk_wawa/source/help/chinuk_wawa.php
@cachang 
adds help file for #1725
=> [chinuk_wawa help]Add help file for chinuk_wawa

experimental/n/naijatype/HISTORY.md, experimental/n/naijatype/LICENSE.md, experimental/n/naijatype/README.md, experimental/n/naijatype/naijatype.kpj, experimental/n/naijatype/source/doc/readme.htm, experimental/n/naijatype/source/naijatype-help.htm, experimental/n/naijatype/source/naijatype.keyman-touch-layout, experimental/n/naijatype/source/naijatype.kmn, experimental/n/naijatype/source/naijatype.kps
I've updated some of the key sizes as they weren't consistent between layers and the space bar was a little too small so that people were touching the punctuation key instead of it. Αlso the ? and ! hadn't been generating the right characters on the default layer so tried to correct that.
=> Naijatype experimental

release/m/masaram_gondi/HISTORY.md, release/m/masaram_gondi/README.md, release/m/masaram_gondi/masaram_gondi.kpj, release/m/masaram_gondi/source/masaram_gondi.keyman-touch-layout, release/m/masaram_gondi/source/masaram_gondi.kmn, release/m/masaram_gondi/source/masaram_gondi.kps, release/m/masaram_gondi/source/readme.htm, release/m/masaram_gondi/source/welcome/welcome.htm
=> [masaram_gondi] Changes on behalf of author

release/sil/sil_devanagari_romanized/source/help/sil_devanagari_romanized.php
This is just an update to the help file to match welcome.htm...except the first paragraph matches what is in README.md.
The welcome.htm needs updating too, but I'll leave that to the authors to do next time they update the keyboard and bump the version number.
=> [sil_devanagari_romanized] Update online help file only

release/m/masaram_gondi/HISTORY.md, release/m/masaram_gondi/masaram_gondi.keyboard_info, release/m/masaram_gondi/masaram_gondi.kpj, release/m/masaram_gondi/source/help/masaram_gondi.php, release/m/masaram_gondi/source/masaram_gondi.kmn, release/m/masaram_gondi/source/masaram_gondi.kps, release/m/masaram_gondi/source/readme.htm, release/m/masaram_gondi/source/welcome/welcome.htm
… help file
* Updated readme.htm to change how font is called so it would display the font when the .kmp is being installed.
* Updated welcome.htm to use tables and changed how font is called so it would display the font when the .kmp is being installed.
* Updated php file to use new welcome.htm code so that tables will be displayed properly.
* Updated `keyboard_info` to use correct font filename.
* Bumped the version number
=> [masaram_gondi] Update welcome.htm to use tables so it can be used in help file

release/e/enggano/README.md, release/e/enggano/enggano.keyboard_info, release/e/enggano/source/help/enggano.php
The .php file is based on the welcome.htm.
Also added supported platform info to README.md and removed blank lines from enggano.keyboard_info.
=> [enggano] add online help and update metadata

release/b/batak/source/help/batak.php, release/sil/sil_akha_act/source/help/sil_akha_act.php
The extra space in the php file made it think there was another layer.
=> [batak_php] Remove spurious space for OSK

release/sil/sil_mali_azerty/HISTORY.md, release/sil/sil_mali_azerty/source/sil_mali_azerty.kmn, release/sil/sil_mali_azerty/source/sil_mali_azerty.kps, release/sil/sil_mali_azerty/source/welcome/welcome.htm
The upcoming kmcmp.exe release will generate errors if a store() name is reused (https://github.com/keymanapp/keyman/pull/6463)
=> [sil_mali_azerty] Remove extraneous store

release/l/lao_phonetic/HISTORY.md, release/l/lao_phonetic/LICENSE.md, release/l/lao_phonetic/README.md, release/l/lao_phonetic/source/help/lao_phonetic.php, release/l/lao_phonetic/source/lao_phonetic.kmn, release/l/lao_phonetic/source/lao_phonetic.kps
The upcoming kmcmp.exe release will generate warnings when store names are re-used. https://github.com/keymanapp/keyman/pull/6463
* Remove the duplicate NY store
* Convert welcome.htm to online help
=> [lao_phonetic] Remove duplicate NY store

release/sil/sil_tai_dam_lao/HISTORY.md, release/sil/sil_tai_dam_lao/LICENSE.md, release/sil/sil_tai_dam_lao/README.md, release/sil/sil_tai_dam_lao/source/sil_tai_dam_lao.kmn, release/sil/sil_tai_dam_lao/source/sil_tai_dam_lao.kps
* Remove the duplicate MESSAGE store
=> [sil_tai_dam_lao] Remove duplicate MESSAGE store

release/itrans/itrans_bengali/HISTORY.md, release/itrans/itrans_bengali/LICENSE.md, release/itrans/itrans_bengali/README.md, release/itrans/itrans_bengali/source/itrans_bengali.kmn, release/itrans/itrans_bengali/source/itrans_bengali.kps
* Remove the duplicate ©RIGHT store
=> [itrans_bengali] Remove duplicate ©RIGHT store

release/u/urdu_phonetic/HISTORY.md, release/u/urdu_phonetic/LICENSE.md, release/u/urdu_phonetic/README.md, release/u/urdu_phonetic/source/urdu_phonetic.kmn, release/u/urdu_phonetic/source/urdu_phonetic.kps
* Remove duplicate store (KEYBOARDVERSION)
=> [urdu_phonetic] Remove duplicate store (KEYBOARDVERSION)

release/fv/fv_dakelh/HISTORY.md, release/fv/fv_dakelh/LICENSE.md, release/fv/fv_dakelh/README.md, release/fv/fv_dakelh/fv_dakelh.kpj, release/fv/fv_dakelh/source/fv_dakelh.kmn, release/fv/fv_dakelh/source/fv_dakelh.kps
Part of #1827 
Tagging @madebybridget
=> [fv_dakelh] Add NCAPS modifier to some rules

release/fv/fv_denesuline_epsilon/HISTORY.md, release/fv/fv_denesuline_epsilon/LICENSE.md, release/fv/fv_denesuline_epsilon/README.md, release/fv/fv_denesuline_epsilon/source/fv_denesuline_epsilon.kmn, release/fv/fv_denesuline_epsilon/source/fv_denesuline_epsilon.kps
=> [fv_denesuline_epsilon] Add NCAPS modifier to some rules

release/fv/fv_diitiidatx/HISTORY.md, release/fv/fv_diitiidatx/LICENSE.md, release/fv/fv_diitiidatx/README.md, release/fv/fv_diitiidatx/source/fv_diitiidatx.kmn, release/fv/fv_diitiidatx/source/fv_diitiidatx.kps
=> [fv_diitiidatx] Add NCAPS modifier to some rules

release/fv/fv_halqemeylem/HISTORY.md, release/fv/fv_halqemeylem/LICENSE.md, release/fv/fv_halqemeylem/README.md, release/fv/fv_halqemeylem/source/fv_halqemeylem.kmn, release/fv/fv_halqemeylem/source/fv_halqemeylem.kps
=> [fv_halqemeylem] Add NCAPS modifier to some rules

release/fv/fv_henqeminem/HISTORY.md, release/fv/fv_henqeminem/LICENSE.md, release/fv/fv_henqeminem/README.md, release/fv/fv_henqeminem/source/fv_henqeminem.kmn, release/fv/fv_henqeminem/source/fv_henqeminem.kps
=> [fv_henqeminem] Add NCAPS modifier to some rules

release/fv/fv_natwits/HISTORY.md, release/fv/fv_natwits/LICENSE.md, release/fv/fv_natwits/README.md, release/fv/fv_natwits/source/fv_natwits.kmn, release/fv/fv_natwits/source/fv_natwits.kps
=> [fv_natwits] Add NCAPS modifier to some rules

release/fv/fv_nsilxcen/HISTORY.md, release/fv/fv_nsilxcen/LICENSE.md, release/fv/fv_nsilxcen/README.md, release/fv/fv_nsilxcen/source/fv_nsilxcen.kmn, release/fv/fv_nsilxcen/source/fv_nsilxcen.kps
=> [fv_nsilxcen] Add NCAPS modifier to some rules

release/fv/fv_nuucaanul/HISTORY.md, release/fv/fv_nuucaanul/LICENSE.md, release/fv/fv_nuucaanul/README.md, release/fv/fv_nuucaanul/source/fv_nuucaanul.kmn, release/fv/fv_nuucaanul/source/fv_nuucaanul.kps
=> [fv_nuucaanul] Add NCAPS modifier to some rules

release/fv/fv_shashishalhem/HISTORY.md, release/fv/fv_shashishalhem/LICENSE.md, release/fv/fv_shashishalhem/README.md, release/fv/fv_shashishalhem/source/fv_shashishalhem.kmn, release/fv/fv_shashishalhem/source/fv_shashishalhem.kps
=> [fv_shashishalhem] Add NCAPS modifier to some rules

release/fv/fv_smalgyax/HISTORY.md, release/fv/fv_smalgyax/LICENSE.md, release/fv/fv_smalgyax/README.md, release/fv/fv_smalgyax/source/fv_smalgyax.kmn, release/fv/fv_smalgyax/source/fv_smalgyax.kps
=> [fv_smalgyax] Add NCAPS modifier to some rules

release/fv/fv_statimcets/HISTORY.md, release/fv/fv_statimcets/LICENSE.md, release/fv/fv_statimcets/README.md, release/fv/fv_statimcets/source/fv_statimcets.kmn, release/fv/fv_statimcets/source/fv_statimcets.kps
=> [fv_statimcets] Add NCAPS modifier to some rules

release/fv/fv_stlatlimxec/HISTORY.md, release/fv/fv_stlatlimxec/LICENSE.md, release/fv/fv_stlatlimxec/README.md, release/fv/fv_stlatlimxec/source/fv_stlatlimxec.kmn, release/fv/fv_stlatlimxec/source/fv_stlatlimxec.kps
=> [fv_stlatlimxec] Add NCAPS modifier to some rules

release/fv/fv_taltan/HISTORY.md, release/fv/fv_taltan/LICENSE.md, release/fv/fv_taltan/README.md, release/fv/fv_taltan/source/fv_taltan.kmn, release/fv/fv_taltan/source/fv_taltan.kps
=> [fv_taltan] Add NCAPS modifier to some rules

release/fv/fv_uwikala/HISTORY.md, release/fv/fv_uwikala/README.md, release/fv/fv_uwikala/source/fv_uwikala.kmn, release/fv/fv_uwikala/source/fv_uwikala.kps
=> [fv_uwikala] Add NCAPS modifier to some rules

release/fv/fv_kwakwala_liqwala/HISTORY.md, release/fv/fv_kwakwala_liqwala/LICENSE.md, release/fv/fv_kwakwala_liqwala/README.md, release/fv/fv_kwakwala_liqwala/fv_kwakwala_liqwala.kpj, release/fv/fv_kwakwala_liqwala/source/fv_kwakwala_liqwala.kmn, release/fv/fv_kwakwala_liqwala/source/fv_kwakwala_liqwala.kps, release/fv/fv_kwakwala_liqwala/source/help/fv_kwakwala_liqwala.php
=> [fv_kwakwala_liqwala] Add NCAPS modifier to some rules

release/s/shan/HISTORY.md, release/s/shan/README.md, release/s/shan/shan.keyboard_info, release/s/shan/shan.kpj, release/s/shan/source/shan.kmn, release/s/shan/source/shan.kps
Small change, only updating language id in kps file to allow applications to detect language correctly. This fixes kern issue in Microsoft Word
=> Updating Language ID

release/h/hausa_ajami_qwerty/HISTORY.md, release/h/hausa_ajami_qwerty/source/hausa_ajami_qwerty.kmn, release/h/hausa_ajami_qwerty/source/hausa_ajami_qwerty.kps
That conflicting rule was producing the wrong output AND I didn't include the .js file in the .kps so I couldn't use the mobile layout.
=> [hausa_ajami_qwerty] Update keyboard to fix two issues

release/m/mon_anonta/HISTORY.md, release/m/mon_anonta/LICENSE.md, release/m/mon_anonta/README.md, release/m/mon_anonta/mon_anonta.kpj, release/m/mon_anonta/source/mon_anonta.kmn, release/m/mon_anonta/source/mon_anonta.kps
Fixes #1848 
* Fix duplicate stores (addK, ldiaK, ldiaU)
=> [mon_anonta] Fix duplicate stores (addK, ldiaK, ldiaU)

release/w/warang_citi/HISTORY.md, release/w/warang_citi/LICENSE.md, release/w/warang_citi/README.md, release/w/warang_citi/source/help/warang_citi.php, release/w/warang_citi/source/warang_citi.kmn, release/w/warang_citi/source/warang_citi.kps, release/w/warang_citi/warang_citi.kpj
Fixes #1916.
1.1 (2022-07-13)
----------------
* Added .js to the keyboard package
=> [warang_citi] add touch layout to the keyboard package

release/o/obolo_chwerty/source/help/obolo_chwerty.php
Fixes #1912.
(Whitespace only changes are line breaks -- different editor changed the line breaks)
=> chore(obolo_chwerty): fix broken links

release/o/orma/README.md, release/o/orma/orma.keyboard_info
More info in readme.md and keyboard_info
=> [orma] Add files via upload

release/c/cabecar/source/help/cabecar.php
`osk` code referenced wrong layer.
=> [cabecar] Update online help file

release/o/old_hungarian/HISTORY.md, release/o/old_hungarian/old_hungarian.keyboard_info, release/o/old_hungarian/old_hungarian.kpj, release/o/old_hungarian/source/help/old_hungarian.php, release/o/old_hungarian/source/old_hungarian.keyman-touch-layout, release/o/old_hungarian/source/old_hungarian.kmn, release/o/old_hungarian/source/readme.htm, release/o/old_hungarian/source/welcome/welcome.htm
=> [old_hungarian] Changes to support &CasedKeys

experimental/k/koreguaje/source/help/koreguaje.php
=> [koreguaje] Add online help

release/b/balochi_scientific/HISTORY.md, release/b/balochi_scientific/LICENSE.md, release/b/balochi_scientific/README.md, release/b/balochi_scientific/balochi_scientific.keyboard_info, release/b/balochi_scientific/balochi_scientific.kpj, release/b/balochi_scientific/source/balochi_scientific.kmn, release/b/balochi_scientific/source/balochi_scientific.kps, release/b/balochi_scientific/source/readme.htm
Fixes #1593 
balochi_latin was handled previously.
=> [balochi_scientific] Update langtag

release/k/khmer_angkor/khmer_angkor.keyboard_info
=> [khmer_angkor] Fix keyboard_info fonts

release/b/bhaiksuki_inscript/source/help/bhaiksuki_inscript.php, release/b/brahmi_inscript/source/help/brahmi_inscript.php, release/s/siddham_inscript/source/help/siddham_inscript.php
Hopefully a minor issue with php files using rightalt when the keyboard is alt.
=> [inscript_php] Update php files to use alt instead of rightalt in osk

release/sil/sil_limbu_typewriter/source/help/sil_limbu_typewriter.php
Doesn't need version increment since only the online help is changing.
=> [sil_limbu_typewriter] correct OSK states

release/sil/sil_yi/HISTORY.md, release/sil/sil_yi/sil_yi.keyboard_info, release/sil/sil_yi/source/sil_yi.kmn, release/sil/sil_yi/source/sil_yi.kps
=> [sil_yi] Remove unsupported language tags

legacy/r/russian-tajik/russian-tajik.keyboard_info
=> [russian-tajik] fix: iOS and Android platforms are not supported

release/gff/gff_harege_fidelat/source/help/gff_harege_fidelat.php, release/gff/gff_mesobe_fidelat/source/help/gff_mesobe_fidelat.php
* Fixes relative images links in Mesobe Fidelat.
* Sets relative image width to 100% in Mesobe Fidelat, and Harege Fidelat.
=> Mesobe Fidelat Help File Image Link Repair. Fixes #2076 .

release/gff/gff_amharic/gff_amharic.keyboard_info
This is an initial attempt at resolution of #2072.
=> GFF Amharic: Web Font Migration to  Noto Ethiopic

experimental/n/naijatype/HISTORY.md, experimental/n/naijatype/source/doc/readme.htm, experimental/n/naijatype/source/naijatype-help.htm, experimental/n/naijatype/source/naijatype.kmn
I just improved the first paragraph of the readme file as I realised it wasn't the most helpful for the Keyman installation page.
=> NaijaType readme update

release/o/otoe_missouria/source/help/otoe_missouria.php
The help file was not displaying properly. The encoding and/or LF got messed up on the initial commit.
=> [otoe_missouria] Fix help file

release/o/otoe_missouria/source/help/otoe_missouria.php
Used the wrong ID for displaying the mobile layout.
=> [otoe_missouria] Fix ID on help file

release/e/ekwtamil99uni/HISTORY.md, release/e/ekwtamil99uni/LICENSE.md, release/e/ekwtamil99uni/README.md, release/e/ekwtamil99uni/ekwtamil99uni.kpj, release/e/ekwtamil99uni/source/ekwtamil99uni-wchart.htm, release/e/ekwtamil99uni/source/ekwtamil99uni.kmn, release/e/ekwtamil99uni/source/ekwtamil99uni.kps, release/e/ekwtamil99uni/source/help/ekwtamil99uni.php, release/e/ekwtamil99uni/source/readme.htm, release/e/ekwtamil99uni/source/welcome/welcome.htm
Fixes part 1 of #2117 
Still need to update main tamil page.
=> [ekwtamil99uni] Fix links in help files

release/sil/sil_euro_latin/HISTORY.md, release/sil/sil_euro_latin/sil_euro_latin.keyboard_info, release/sil/sil_euro_latin/source/sil_euro_latin.kmn, release/sil/sil_euro_latin/source/sil_euro_latin.kps
Relates to keymanapp/keyman#8118
=> fix(sil_euro_latin): remove duplicate `sq` language code

release/sil/sil_euro_latin/HISTORY.md, release/sil/sil_euro_latin/sil_euro_latin.keyboard_info, release/sil/sil_euro_latin/source/sil_euro_latin.kmn, release/sil/sil_euro_latin/source/sil_euro_latin.kps
Relates to keymanapp/keyman#8118
=> fix(sil_euro_latin): repeated ik, ff, gn, qu language codes

experimental/a/alephwithbeth/HISTORY.md, experimental/a/alephwithbeth/alephwithbeth.kpj, experimental/a/alephwithbeth/source/alephwithbeth.kmn, experimental/a/alephwithbeth/source/alephwithbeth.kps, experimental/a/alephwithbeth/source/help/alephwithbeth.php, experimental/a/alephwithbeth/source/readme.htm, experimental/a/alephwithbeth/source/welcome/welcome.htm
Updated readme, website, author.
=> [alephwithbeth] 1.0.1

release/t/txo_toto/HISTORY.md, release/t/txo_toto/source/txo_toto.keyman-touch-layout, release/t/txo_toto/source/txo_toto.kmn, release/t/txo_toto/txo_toto.kpj
=> [txo_toto] Enable reaching shift layer on touch layout

experimental/a/alephwithbeth/HISTORY.md, experimental/a/alephwithbeth/alephwithbeth.kpj, experimental/a/alephwithbeth/source/alephwithbeth.keyman-touch-layout, experimental/a/alephwithbeth/source/alephwithbeth.kmn, experimental/a/alephwithbeth/source/alephwithbeth.kvks
* set K_HYPHEN output to be a _maqef_ (Hebrew letter)
* added touch-optimized layout for phones
=> [alephwithbeth] 1.0.5

release/o/old_hungarian/HISTORY.md
Modified HISTORY.md to 1.6 version
=> Modified HISTORY.md

release/o/old_hungarian/HISTORY.md, release/o/old_hungarian/old_hungarian.kpj, release/o/old_hungarian/source/old_hungarian.keyman-touch-layout, release/o/old_hungarian/source/old_hungarian.kmn
@LornaSIL @DavidLRowe This Pull request resolve https://github.com/keymanapp/keyboards/issues/2203#issue-1697504285 Issue
=> Resolved Old Hungarian numbers fault in shift layer Old Hungarian layout for mobile device

release/o/old_hungarian/HISTORY.md, release/o/old_hungarian/LICENSE.md, release/o/old_hungarian/old_hungarian.kpj, release/o/old_hungarian/source/old_hungarian.kmn, release/o/old_hungarian/source/old_hungarian.kps
=> [old_hungarian] Add caps lock support for digit keys

release/gff/gff_tigrinya_ethiopia/HISTORY.md, release/gff/gff_tigrinya_ethiopia/LICENSE.md, release/gff/gff_tigrinya_ethiopia/README.md, release/gff/gff_tigrinya_ethiopia/gff_tigrinya_ethiopia.kpj, release/gff/gff_tigrinya_ethiopia/source/gff_tigrinya_ethiopia.kmn, release/gff/gff_tigrinya_ethiopia/source/gff_tigrinya_ethiopia.kps, release/gff/gff_tigrinya_ethiopia/source/help/gff_tigrinya_ethiopia.php, release/gff/gff_tigrinya_ethiopia/source/welcome.htm
The minimal updates to address issue #2214
=> GFF Tigrinya-Ethiopia v1.3.14

release/gff/gff_harari/HISTORY.md, release/gff/gff_harari/README.md, release/gff/gff_harari/gff_harari.kpj, release/gff/gff_harari/source/gff_harari.keyman-touch-layout, release/gff/gff_harari/source/gff_harari.kmn, release/gff/gff_harari/source/gff_harari.kps, release/gff/gff_harari/source/welcome.htm
This update fixes two keys that were not triggering next-layers as expected. Also missing labiovelar popup keys were added.
=> GFF Harari v1.0.1

release/h/himyarit_musnad/HISTORY.md, release/h/himyarit_musnad/LICENSE.md, release/h/himyarit_musnad/README.md, release/h/himyarit_musnad/himyarit_musnad.kpj, release/h/himyarit_musnad/source/help/himyarit_musnad.php, release/h/himyarit_musnad/source/himyarit_musnad.keyman-touch-layout, release/h/himyarit_musnad/source/himyarit_musnad.kmn, release/h/himyarit_musnad/source/himyarit_musnad.kps, release/h/himyarit_musnad/source/readme.htm, release/h/himyarit_musnad/source/welcome.htm
This submission of version 1.1 is made on behalf of the author,  @RiyadhAlfareh .
Version 1.1 adds Arabic letters to the keycaps of the touch layout for the benefit of greater clarity and ease of typing.
=> Himyarit Musnad v1.1

release/gff/gff_tigre/source/help/gff_tigre.php, release/gff/gff_tigrinya_eritrea/source/help/gff_tigrinya_eritrea.php
=> Minimal Fixes to Resolve Issue 2254

legacy/gff/gff-awn-powerpack-7/DEPRECATED.md, legacy/gff/gff-tir-et-powerpack-7/DEPRECATED.md, legacy/gff/gff_awn_7/DEPRECATED.md, release/gff/gff_awngi_xamtanga/gff_awngi_xamtanga.keyboard_info
=> [gff_dep] Deprecate gff_awn_7 etc

release/a/ahom_star/HISTORY.md, release/a/ahom_star/LICENSE.md, release/a/ahom_star/README.md, release/a/ahom_star/ahom_star.kpj, release/a/ahom_star/source/ahom_star.kmn, release/a/ahom_star/source/ahom_star.kps
=> [ahom_star] Remove spurious start menu items

experimental/n/nasa_yuwe/HISTORY.md, experimental/n/nasa_yuwe/LICENSE.md, experimental/n/nasa_yuwe/README.md, experimental/n/nasa_yuwe/nasa_yuwe.keyboard_info, experimental/n/nasa_yuwe/nasa_yuwe.kpj, experimental/n/nasa_yuwe/source/help/nasa_yuwe.php, experimental/n/nasa_yuwe/source/nasa_yuwe.kmn, experimental/n/nasa_yuwe/source/nasa_yuwe.kps
=> [nasa_yuwe] Updates for embedded OSK bug

release/t/tai_tham_my/source/help/tai_tham_my.php
=> [tai_tham_my] fix a link in the php file

release/o/old_hungarian/HISTORY.md, release/o/old_hungarian/old_hungarian.kpj, release/o/old_hungarian/source/old_hungarian.keyman-touch-layout, release/o/old_hungarian/source/old_hungarian.kmn
Update Old Hugarian layout for mobile devices: added digital num. punctuation marks and quotation marks to ralt-shift level.
ISSUE #2294
=> Update Old Hugarian layout for mobile devices: added digital nums. and punctuation marks to ralt-shift

release/n/nisenan/HISTORY.md, release/n/nisenan/LICENSE.md, release/n/nisenan/README.md, release/n/nisenan/nisenan.kpj, release/n/nisenan/source/help/nisenan.php, release/n/nisenan/source/nisenan.keyboard_info, release/n/nisenan/source/nisenan.kmn, release/n/nisenan/source/nisenan.kps, release/n/nisenan/source/readme.htm, release/n/nisenan/source/welcome.htm, release/s/swanalekha_malayalam/HISTORY.md, release/s/swanalekha_malayalam/LICENSE.md, release/s/swanalekha_malayalam/README.md, release/s/swanalekha_malayalam/source/swanalekha_malayalam.kmn, release/s/swanalekha_malayalam/source/swanalekha_malayalam.kps, release/s/swanalekha_malayalam/swanalekha_malayalam.kpj, release/w/warang_citi/HISTORY.md, release/w/warang_citi/LICENSE.md, release/w/warang_citi/README.md, release/w/warang_citi/source/help/warang_citi.php, release/w/warang_citi/source/readme.htm, release/w/warang_citi/source/warang_citi.kmn, release/w/warang_citi/source/warang_citi.kps, release/w/warang_citi/source/welcome/welcome.htm, release/w/warang_citi/warang_citi.kpj
=> [2302_source] Changes required to address issue 2302

release/fv/fv_nsilxcen/source/help/fv_nsilxcen.php
Updated touch layout table to match new mobile layout.
Approved by @caforbes
=> updated touch layout table

legacy/g/grkpoly2/source/help/grkpoly2.php
Fixes #1647 (or least helps document it better).
=> [grkpoly2] Emphasize need to turn on Simulate AltGr

legacy/m/mozhi_1_1_0/source/help/mozhi_1_1_0.php
=> [mozhi_php] Experiment to see if pagename changes help index

legacy/o/orviet10/orviet10.keyboard_info, legacy/v/vietweb11/DEPRECATED.md
=> [vietweb11] Deprecate keyboard

legacy/b/buang/source/help/buang.php, legacy/g/gaelic/source/help/gaelic.php, legacy/k/kmhmu/source/help/kmhmu.php, legacy/m/malta/source/help/malta.php, legacy/s/slovenian/source/help/slovenian.php, legacy/s/swiss_french/source/help/swiss_french.php, release/s/sxava/sxava.keyboard_info, release/w/warang_citi/source/help/warang_citi.php
=> [php_more] More deprecations

release/n/northern_sierra_miwok/source/northern_sierra_miwok.keyboard_info
Fixes #2342 and replaces #2348
=> [northern_sierra_miwok] Delete spurious keyboard_info file

release/fv/fv_taltan/HISTORY.md, release/fv/fv_taltan/LICENSE.md, release/fv/fv_taltan/fv_taltan.kpj, release/fv/fv_taltan/source/fv_taltan.keyman-touch-layout, release/fv/fv_taltan/source/fv_taltan.kmn
- Updated and simplified rules
- Changed characters to single code point outputs where possible
- Centred mobile keyboard
- Approved by @caforbes
=> [fv_taltan] QOL updates, updated rules, centred mobile keyboard

release/o/old_hungarian/HISTORY.md, release/o/old_hungarian/old_hungarian.kpj, release/o/old_hungarian/source/old_hungarian.keyman-touch-layout, release/o/old_hungarian/source/old_hungarian.kmn, release/o/old_hungarian/source/old_hungarian.kvks
=> [old_hungarian] Update mobile layout longpress buttons

experimental/e/elfdalian/source/help/elfdalian.php
This is just updating the help file so it will show online. (The naming was wrong.) Also, the osk stuff didn't match actual layer names.
=> [elfdalian] Rename help file and fix up osk code

resources/help-keyman-com.sh
This will open a pull request for keyboard layout documentation changes, so then the changes will go through CI, which will avoid the current issue where broken links in keyboards cause other PRs to fail CI.
It will also mean that we no longer push to master for keyboard help publishing, which will be cleaner.
=> chore: update help repo as a PR

release/fv/fv_nuucaanul/HISTORY.md, release/fv/fv_nuucaanul/LICENSE.md, release/fv/fv_nuucaanul/README.md, release/fv/fv_nuucaanul/fv_nuucaanul.keyboard_info, release/fv/fv_nuucaanul/fv_nuucaanul.kpj, release/fv/fv_nuucaanul/source/fv_nuucaanul.keyman-touch-layout, release/fv/fv_nuucaanul/source/fv_nuucaanul.kmn, release/fv/fv_nuucaanul/source/fv_nuucaanul.kps, release/fv/fv_nuucaanul/source/fv_nuucaanul_kmw_help.htm, release/fv/fv_nuucaanul/source/help/fv_nuucaanul.php, release/fv/fv_nuucaanul/source/readme.htm, release/fv/fv_nuucaanul/source/welcome/welcome.htm
Update to single codepoints where possible, change name to better reflect language name, center mobile keyboard, clean rules.
=> fv nuucaanul

release/fv/fv_kwakwala_liqwala/HISTORY.md, release/fv/fv_kwakwala_liqwala/fv_kwakwala_liqwala.kpj, release/fv/fv_kwakwala_liqwala/source/fv_kwakwala_liqwala.kmn, release/fv/fv_kwakwala_liqwala/source/fv_kwakwala_liqwala_kmw_help.htm, release/fv/fv_kwakwala_liqwala/source/help/fv_kwakwala_liqwala.php, release/fv/fv_kwakwala_liqwala/source/welcome/welcome.htm
Updated keyboard name to better reflect language name, corrected spelling in documentation. Approved by @caforbes
=> Fv kwakwala liqwala

release/fv/fv_dene_zhatie/HISTORY.md, release/fv/fv_dene_zhatie/README.md, release/fv/fv_dene_zhatie/fv_dene_zhatie.kpj, release/fv/fv_dene_zhatie/source/fv_dene_zhatie.keyman-touch-layout, release/fv/fv_dene_zhatie/source/fv_dene_zhatie.kmn, release/fv/fv_dene_zhatie/source/fv_dene_zhatie.kps, release/fv/fv_dene_zhatie/source/welcome/welcome.htm
Updates per @DavidLRowe 's recommendations.
=> Update to version and .keyman-touch-layout file

release/fv/fv_nuxalk/HISTORY.md, release/fv/fv_nuxalk/LICENSE.md, release/fv/fv_nuxalk/fv_nuxalk.kpj, release/fv/fv_nuxalk/source/fv_nuxalk.keyman-touch-layout, release/fv/fv_nuxalk/source/fv_nuxalk.kmn, release/fv/fv_nuxalk/source/fv_nuxalk.kps, release/fv/fv_nuxalk/source/help/fv_nuxalk.php
Added missing L key, made keys slightly larger.
=> [FV nuxalk] added missing key 

release/fv/fv_uwikala/HISTORY.md, release/fv/fv_uwikala/README.md, release/fv/fv_uwikala/fv_uwikala.keyboard_info, release/fv/fv_uwikala/fv_uwikala.kpj, release/fv/fv_uwikala/source/fv_uwikala.keyman-touch-layout, release/fv/fv_uwikala/source/fv_uwikala.kmn, release/fv/fv_uwikala/source/fv_uwikala.kps, release/fv/fv_uwikala/source/fv_uwikala_help.htm, release/fv/fv_uwikala/source/help/fv_uwikala.php, release/fv/fv_uwikala/source/readme.htm, release/fv/fv_uwikala/source/welcome/welcome.htm
cleaned up mobile rules, added rule to backspace accents instead of whole character, centered mobile layout
=> [fv_uwikala] changed keyboard name

experimental/gff/gff_sbs/HISTORY.md, experimental/gff/gff_sbs/README.md, experimental/gff/gff_sbs/gff_sbs.kpj, experimental/gff/gff_sbs/source/gff_sbs.kmn, experimental/gff/gff_sbs/source/gff_sbs.kps, experimental/gff/gff_sbs/source/gff_sbs.kvks, experimental/gff/gff_sbs/source/help/gff_sbs.php, experimental/gff/gff_sbs/source/welcome.htm
This PR fixes #2482 .
The `welcome.htm` and `gff_sbs.php` files both have the needed link corrections.  The correction was tested successfully on the `welcome.htm` page.
@DavidLRowe's earlier suggestion for the `README.md` file have also been applied.  Thanks @DavidLRowe !
=> GFF Sheek Bakrii Saphaloo Qubee Keyboard v1.0.1

experimental/gff/gff_sbs/HISTORY.md, experimental/gff/gff_sbs/gff_sbs.kpj, experimental/gff/gff_sbs/source/gff_sbs.kmn, experimental/gff/gff_sbs/source/gff_sbs.kps
=> GFF Sheek Bakrii Saphaloo Qubee Keyboard v1.0.2

release/fv/fv_hailzaqvla/HISTORY.md, release/fv/fv_hailzaqvla/LICENSE.md, release/fv/fv_hailzaqvla/README.md, release/fv/fv_hailzaqvla/fv_hailzaqvla.keyboard_info, release/fv/fv_hailzaqvla/fv_hailzaqvla.kpj, release/fv/fv_hailzaqvla/source/fv_hailzaqvla.keyman-touch-layout, release/fv/fv_hailzaqvla/source/fv_hailzaqvla.kmn, release/fv/fv_hailzaqvla/source/fv_hailzaqvla.kps, release/fv/fv_hailzaqvla/source/help/fv_hailzaqvla.php, release/fv/fv_hailzaqvla/source/readme.htm, release/fv/fv_hailzaqvla/source/welcome.htm
Corrected language and keyboard name, added info on typing glottal stop while using Google Docs in Chrome, centred mobile layout, updated combining apostrophe to true deadkey.
=> [FV hailzaqvla] Corrected language spelling, updated info and keys

release/fv/fv_nsilxcen/HISTORY.md, release/fv/fv_nsilxcen/LICENSE.md, release/fv/fv_nsilxcen/fv_nsilxcen.keyboard_info, release/fv/fv_nsilxcen/fv_nsilxcen.kpj, release/fv/fv_nsilxcen/source/fv_nsilxcen.keyman-touch-layout, release/fv/fv_nsilxcen/source/fv_nsilxcen.kmn, release/fv/fv_nsilxcen/source/fv_nsilxcen.kps, release/fv/fv_nsilxcen/source/help/fv_nsilxcen.php
Added missing mid-dot key and added č̓ to long press on mobile layout, centred mobile layout, cleaned up rules, updated help and history.
=> [FV nsilxcen] Added missing key and characters

experimental/h/hcesar/HISTORY.md, experimental/h/hcesar/LICENSE.md, experimental/h/hcesar/README.md, experimental/h/hcesar/hcesar.keyboard_info, experimental/h/hcesar/hcesar.kpj, experimental/h/hcesar/source/hcesar.kmn, experimental/h/hcesar/source/hcesar.kps, experimental/h/hcesar/source/hcesar.kvks, experimental/h/hcesar/source/help/hcesar.php, experimental/h/hcesar/source/readme.htm, experimental/h/hcesar/source/welcome/welcome.htm
Fixed comma and period keys according to official layout and most historical typewriters used (de facto).
=> hcesar 1.1.1

release/k/knyaw/HISTORY.md, release/k/knyaw/knyaw.kpj, release/k/knyaw/source/help/knyaw.php, release/k/knyaw/source/knyaw.keyman-touch-layout, release/k/knyaw/source/knyaw.kmn
I had planned to just add the help file, but then I realized the touch layout didn't allow for going to shift layer.
=> [knyaw] Added help file and fixed touch layout

release/packages/fv_all/HISTORY.md, release/packages/fv_all/source/fv_all.kps.in
Relates to keymanapp/keyman#11013
This updates the fv_all package version to incorporate all the recent FV updates.
=> chore: Update fv_all keyboard version

release/fv/fv_secwepemctsin/source/help/fv_secwepemctsin.php
=> fv_secwepemctsin - typo

experimental/s/shebek/shebek.keyboard_info
I'm hoping this will work, but I'm not sure if the directionality will work properly.
=> [shebek] Experiment to add Arabic descriptive text in keyboard_info

experimental/kreative/kreative_sitelenpona_ucsur/kreative_sitelenpona_ucsur.keyboard_info
As requested in https://github.com/keymanapp/keyboards/pull/2670
=> [kreative_sitelenpona_ucsur] Add fonts to keyboard_info

package-lock.json, package.json, release/b/burushaski_girminas/source/burushaski_girminas.kps, release/el/el_dinka/source/el_dinka.kps, release/el/el_naija/source/el_naija.kps, release/el/el_pan_sahelian/source/el_pan_sahelian.kps, release/g/galaxie_greek_positional/source/galaxie_greek_positional.kps, release/gff/gff_amh_7/source/gff_amh_7.kps, release/gff/gff_geez/source/gff_geez.kps, release/packages/fv_all/build.sh, release/sil/sil_greek_polytonic/source/sil_greek_polytonic.kps, release/t/thamizha_anjal_paangu/source/thamizha_anjal_paangu.kps, release/t/thamizha_bamini/source/thamizha_bamini.kps, release/t/thamizha_new_typewriter/source/thamizha_new_typewriter.kps, release/t/thamizha_tamil99_ext/source/thamizha_tamil99_ext.kps, release/t/tibetan_direct_input/source/tibetan_direct_input.kps, release/t/tibetan_ewts/source/tibetan_ewts.kps, release/v/vm_tamil_modular/source/vm_tamil_modular.kps, release/v/vm_tamil_typewriter/source/vm_tamil_typewriter.kps
Updating kmc compiled to current beta which required the following changes
* Add fonts to .kps files (I cherrypicked 74971f28c76aa802a6a25a5a50ffee8e32a920f2 and 3e9186595bf1e58355a505003a0962593b4876d2)
* Add definitions in the release/packages/fv_all/build.sh script
=> [staging-17.0] Update kmc to 17.0.318-beta

release/gff/gff_gurage_legacy/HISTORY.md, release/gff/gff_gurage_legacy/LICENSE.md, release/gff/gff_gurage_legacy/README.md, release/gff/gff_gurage_legacy/gff_gurage_legacy.kpj, release/gff/gff_gurage_legacy/source/gff_gurage_legacy.kmn, release/gff/gff_gurage_legacy/source/gff_gurage_legacy.kps, release/gff/gff_gurage_legacy/source/help/gff_gurage_legacy.php
Version bump to avoid conflicts with v0.11. Fixes Keyboards issue #2720.
=> GFF Gurage Legacy Keyboard v0.51

release/packages/fv_all/HISTORY.md, release/packages/fv_all/source/fv_all.kps.in
Updates fv_all.kmp keyboard package to include recent updates, notably
* Add fv_nlakapamuxcheen (#2731)
* Add desktop keyboard for fv_nlha7kapmxtsin (#2686)
=> [fv_all] Bump version to 12.9

release/sil/sil_khmer/sil_khmer.kpj, release/sil/sil_khmer/source/sil_khmer.kmn
The versions are corrected. Thank you!
=> chore(sil_khmer): update versions in .kmn and .kpj file

release/fv/fv_nlakapamuxcheen/HISTORY.md, release/fv/fv_nlakapamuxcheen/fv_nlakapamuxcheen.kpj, release/fv/fv_nlakapamuxcheen/source/fv_nlakapamuxcheen.kmn, release/fv/fv_nlakapamuxcheen/source/fv_nlakapamuxcheen.kps, release/fv/fv_nlekepmxcin/fv_nlekepmxcin.keyboard_info
Corrected a few typos and mistake in keyboard name I made.
=> [fv nlakapamuxcheen and fv_nlekepmxcin] Correcting typos

package-lock.json, package.json
Updates the staging branch to use the recent` kmc-17.0.325` release
=> [staging-17.0] Update to kmc-17.0.325 stable

experimental/k/kirat_rai_inscript/kirat_rai_inscript.keyboard_info
Can't see the font when typing in the online keyboard unless the font is installed.
=> [kirat_rai_inscript] Add OSK font information

release/fv/fv_haisla/source/help/fv_haisla.php
Added missing table info to fix the table in .php file.
=> [fv_haisla] Fixed table in .php

experimental/c/chorasmian/chorasmian.keyboard_info, experimental/c/chorasmian/source/help/chorasmian.php, experimental/e/elymaic/source/help/elymaic.php
For experimental Elymaic and Chorasmian
=> [help_php] Add online help files and add font to keyboard_info

legacy/c/cs-pinyin/cs-pinyin.keyboard_info, legacy/d/dvorak/dvorak.keyboard_info, legacy/e/european2/european2.keyboard_info, legacy/l/latin_american/latin_american.keyboard_info, legacy/n/nigeria unicode underline/nigeria unicode underline.keyboard_info, legacy/t/tengwar/tengwar.keyboard_info, legacy/u/us/us.keyboard_info, legacy/u/us_dvorak/us_dvorak.keyboard_info, legacy/u/us_dvorak_lh/us_dvorak_lh.keyboard_info, legacy/u/us_dvorak_rh/us_dvorak_rh.keyboard_info, legacy/u/us_int/us_int.keyboard_info
=> [legacy_lang_tags] Update wrong language tags in legacy keyboards

release/k/kui_odia_winscript/HISTORY.md, release/k/kui_odia_winscript/source/kui_odia_winscript.kmn, release/k/kui_odia_winscript/source/kui_odia_winscript.kps
I forgot to change the name in one place.
=> [kui_odia_winscript] Adjust kps file to reflect correct keyboard name

legacy/c/cs-pinyin/cs-pinyin.keyboard_info
Fixes: keymanapp/keyman.com#458
Fixes: KEYMAN-COM-12V
=> fix(cs-pinyin): use published languages format in .keyboard_info

release/sil/sil_mende_kikakui/HISTORY.md, release/sil/sil_mende_kikakui/source/sil_mende_kikakui-help.htm, release/sil/sil_mende_kikakui/source/sil_mende_kikakui.kmn
I've never done one of these before, but this keyboard especially needs it since the OSK is worthless.
I only found 2 keyboards where this file is actually working: [naijatype ](https://keymanweb.com/#ha,Keyboard_naijatype)and [sil_euro_latin](https://keymanweb.com/#aae,Keyboard_sil_euro_latin). No other keyboards have a working file. So, I tried to follow the example from these two keyboards where it does work. 
My help file is much longer than the other two, so I'm not sure how it will display, but I thought I'd try it.
=> [sil_mende_kikakui] Update to add a KeymanWeb help file

release/a/arbore/source/help/arbore.php
Replaced <code> formatting with <kbd>, attempted to fix formatting
=> Arbore release

release/f/formosa/LICENSE.md, release/f/formosa/source/formosa.kmn, release/f/formosa/source/formosa.kps
note: no version bump needed because original formosa.kmn failed deployment.
Full discussion here: https://github.com/keymanapp/keyboards/pull/2886#issuecomment-2209571960
=> fix(formosa): refactor `nul` rules in main group

release/fv/fv_hulquminum_combine/source/help/fv_hulquminum_combine.php
Missed adding in a space - fixed now!
=> [FV hulquminum combine] Fixed table

release/fv/fv_ojibwa_ifinal_rdot/source/help/fv_ojibwa_ifinal_rdot.php
Fixes broken link in keyboard help deployment
latest is keymanapp/help.keyman.com#1390
=> [fv_ojibwa_ifinal_rdot] Fix help link to pdf

release/packages/fv_all/HISTORY.md, release/packages/fv_all/keyboards.csv, release/packages/fv_all/source/fv_all.kps.in
Add two new keyboards to fv_all.kmp
* fv_ojibwa_ifinal #2890
* fv_ojibwa_ifinal_rdot #2891
=> [fv_all] Add fv_ojibwa_ifinal and fv_ojibwa_ifinal_rdot

release/fv/fv_hulquminum_combine/HISTORY.md, release/fv/fv_hulquminum_combine/source/fv_hulquminum_combine.kmn, release/fv/fv_hulquminum_combine/source/fv_hulquminum_combine.kps, release/fv/fv_hulquminum_combine/source/help/fv_hulquminum_combine.php, release/fv/fv_hulquminum_combine/source/welcome/welcome.htm
- Tidied documentation
- Added alternate names
=> [FV hulquminum combine] Minor updates

release/sil/sil_hebrew/HISTORY.md, release/sil/sil_hebrew/source/sil_hebrew.kmn, release/sil/sil_hebrew/source/sil_hebrew.kvks
When I tested the online one on my home computer it was seeing square boxes. So, I realized I hadn't set the new font properly.
=> [sil_hebrew] Changed font for OSK to use KbdHebr instead

experimental/r/runeboard/source/help/runeboard.php
Updated help file to avoid confusion about repositioning of the ZWJ.
=> Runeboard php

release/l/linear_b/source/linear_b.kps
Fixes #2980 
No version number increment needed.
=> [linear_b] Delete spurious description.

release/i/idoma/HISTORY.md, release/i/idoma/source/idoma.kmn, release/i/idoma/source/idoma.kps, release/t/taigi_viet_telex/source/help/taigi_viet_telex.php
- Idoma - I had missed that there was no description in the .kps. (version bumped)
- taigi_viet_telex - I had missed that there was no php file (no version bump needed)
=> [idoma_tvt] Update idoma and taigi_viet_telex files

release/fv/fv_lekwungen/source/help/fv_lekwungen.php
- fix css table for mobile layout
- remove shift layer image for desktop
=> [fv_lekwungen] - help doc formatting

release/fv/fv_halqemeylem/HISTORY.md, release/fv/fv_halqemeylem/fv_halqemeylem.kpj, release/fv/fv_halqemeylem/source/fv_halqemeylem.kmn, release/fv/fv_halqemeylem/source/help/fv_halqemeylem.php, release/fv/fv_halqemeylem/source/welcome/welcome.htm
- updated php and welcome.htm help files
- tiny version bump
=> [fv_halqemeylem] - help docs, version bump

release/fv/fv_sencoten/source/help/fv_sencoten.php
=> [fv_sencoten] - php help file css fix

package-lock.json, package.json, release/m/masaram_gondi/source/masaram_gondi.kmn
This fixes three compiler issues:
fix(developer): check HISTORY.md to get last modified date for keyboard_info and model_info (keymanapp/keyman#11808)
fix(developer): prevent non-BMP characters in key part of rule (keymanapp/keyman#11807)
chore(developer): clarify project upgrade messages about file locations (keymanapp/keyman#11820)
Fixes: keymanapp/api.keyman.com#259
=> chore: upgrade kmc from 17.0.326 to 17.0.328

experimental/n/naijatype/HISTORY.md, experimental/n/naijatype/source/naijatype.kmn, experimental/n/naijatype/source/naijatype.kps
=> [naijatype] fixes indented new line in kps description tag

release/p/phonetic_farsi/source/help/phonetic_farsi.php
Help file isn't showing up properly. https://help.keyman.com/keyboard/phonetic_farsi/1.0/phonetic_farsi
I think both the header statement was formatted wrong and all the divs maybe confused things.
=> [phonetic_farsi] Update online help file

release/t/taichow/HISTORY.md, release/t/taichow/source/help/taichow.php, release/t/taichow/source/taichow.kmn, release/t/taichow/source/welcome.htm
I found thi rule is not very universal in every Goetian romanization. I want to delete this rule.
Sorry for inconvinience.
=> [taichow] Update keyboard to delete one rule ya> yia

release/o/old_hungarian/HISTORY.md, release/o/old_hungarian/source/old_hungarian.keyman-touch-layout, release/o/old_hungarian/source/old_hungarian.kmn
On branch master
Your branch is up to date with 'origin/master'.
Changes to be committed:
modified:   release/o/old_hungarian/HISTORY.md
modified:   release/o/old_hungarian/source/old_hungarian.keyman-touch-layout
modified:   release/o/old_hungarian/source/old_hungarian.kmn
Fixes: #3045
=> [old_hungarian] An aK-eK problem resolved on mobile devs

release/o/old_hungarian/HISTORY.md, release/o/old_hungarian/source/old_hungarian.keyman-touch-layout, release/o/old_hungarian/source/old_hungarian.kmn
On branch aK_eK_unicode
Changes to be committed:
modified:   release/o/old_hungarian/HISTORY.md
modified:   release/o/old_hungarian/source/old_hungarian.keyman-touch-layout
modified:   release/o/old_hungarian/source/old_hungarian.kmn
=> [old_hungarian][mobile]apperence ak ek resolved

release/p/pinyin_typer/source/help/pinyin_typer.php
Rename `pinyin.php` to `pinyin_typer.php` and remove copyright year.
=> [pinyin_typer] Rename help

release/y/yiddish_pasekh/HISTORY.md, release/y/yiddish_pasekh/source/yiddish_pasekh.kmn
Alert Dr Jay when keyboard is merged and updated:
https://community.software.sil.org/t/yiddish-pasekh-keyboard-yud-character-stopped-working/9142/3
=> [yiddish_pasekh] Fix bugs from last update

release/g/greek_polytonic_plus/source/help/greek_polytonic_plus.php
See https://github.com/keymanapp/keyboards/issues/3184
Fixes #3184 
FYI: @DP-Upstate
=> [greek_polytonic_plus] Correction to PHP file

release/g/greek_polytonic_plus/source/help/greek_polytonic_plus.php
Addresses @mcdurdin comment:
https://github.com/keymanapp/keyboards/pull/3188
=> [greek_polytonic_plus] Update php file

release/a/avestan_phonetic/source/avestan_phonetic.kps, release/athinkra/athinkra_vai/source/athinkra_vai.kps, release/bj/bj_mista_wasaha_cree/source/bj_mista_wasaha_cree.kps, release/d/dives_akuru_inscript/source/dives_akuru_inscript.kps, release/e/esperuni/source/esperuni.kps, release/gautami/gautami_devanagari/source/gautami_devanagari.kps, release/itrans/itrans_bengali/source/itrans_bengali.kps, release/itrans/itrans_devanagari_hindi/source/itrans_devanagari_hindi.kps, release/itrans/itrans_devanagari_sanskrit_vedic/source/itrans_devanagari_sanskrit_vedic.kps, release/itrans/itrans_gujarati/source/itrans_gujarati.kps, release/itrans/itrans_gurmukhi/source/itrans_gurmukhi.kps, release/itrans/itrans_odia/source/itrans_odia.kps, release/s/sogdian_phonetic/source/sogdian_phonetic.kps, release/sil/sil_tai_dam/source/sil_tai_dam.kps, release/sil/sil_tai_dam_typewriter/source/sil_tai_dam_typewriter.kps, release/t/todhri/source/todhri.kps, release/y/yezidi/source/yezidi.kps
Addresses #3191 as well as other keyboards with issues.
Since this is only displayed on the webpage and not in a keyboard package I don't think a version bump is necessary.
=> [examples] Fix up .kps files for correct structure

release/sil/sil_pan_africa_mnemonic/HISTORY.md, release/sil/sil_pan_africa_mnemonic/LICENSE.md, release/sil/sil_pan_africa_mnemonic/README.md, release/sil/sil_pan_africa_mnemonic/source/sil_pan_africa_mnemonic.kmn, release/sil/sil_pan_africa_mnemonic/source/sil_pan_africa_mnemonic.kps, release/sil/sil_pan_africa_mnemonic/source/sil_pan_africa_mnemonic.kvks, release/sil/sil_pan_africa_positional/HISTORY.md, release/sil/sil_pan_africa_positional/LICENSE.md, release/sil/sil_pan_africa_positional/README.md, release/sil/sil_pan_africa_positional/source/sil_pan_africa_positional.kmn, release/sil/sil_pan_africa_positional/source/sil_pan_africa_positional.kps, release/sil/sil_pan_africa_positional/source/sil_pan_africa_positional.kvks
=> [sil_pan_africa] update fub langage tag to mnemonic and postional

release/basic/basic_kbdlisub/HISTORY.md, release/basic/basic_kbdlisub/LICENSE.md, release/basic/basic_kbdlisub/README.md, release/basic/basic_kbdlisub/basic_kbdlisub.kpj, release/basic/basic_kbdlisub/source/basic_kbdlisub.kmn, release/basic/basic_kbdlisub/source/basic_kbdlisub.kps, release/basic/basic_kbdlisub/source/basic_kbdlisub.kvks, release/basic/basic_kbdlisub/source/help/basic_kbdlisub.php, release/basic/basic_kbdlisub/source/readme.htm, release/basic/basic_kbdlisub/source/welcome/welcome.htm, release/basic/basic_kbdlisus/HISTORY.md, release/basic/basic_kbdlisus/LICENSE.md, release/basic/basic_kbdlisus/README.md, release/basic/basic_kbdlisus/basic_kbdlisus.kpj, release/basic/basic_kbdlisus/source/basic_kbdlisus.kmn, release/basic/basic_kbdlisus/source/basic_kbdlisus.kps, release/basic/basic_kbdlisus/source/basic_kbdlisus.kvks, release/basic/basic_kbdlisus/source/readme.htm, release/basic/basic_kbdlisus/source/welcome/welcome.htm, release/sil/sil_lisu_basic/HISTORY.md, release/sil/sil_lisu_basic/LICENSE.md, release/sil/sil_lisu_basic/README.md, release/sil/sil_lisu_basic/source/sil_lisu_basic.kmn, release/sil/sil_lisu_basic/source/sil_lisu_basic.kps, release/sil/sil_lisu_standard/HISTORY.md, release/sil/sil_lisu_standard/LICENSE.md, release/sil/sil_lisu_standard/README.md, release/sil/sil_lisu_standard/source/sil_lisu_standard.kmn, release/sil/sil_lisu_standard/source/sil_lisu_standard.kps
Address 4 Lisu kbds from #3221
=> [Lisu] Update 4 Lisu keyboards to remove lbc and update other tags

release/a/aramaic_hebrew/HISTORY.md, release/a/aramaic_hebrew/LICENSE.md, release/a/aramaic_hebrew/README.md, release/a/aramaic_hebrew/source/aramaic_hebrew.kmn, release/a/aramaic_hebrew/source/aramaic_hebrew.kps, release/packages/syriac_aramaic/HISTORY.md, release/packages/syriac_aramaic/LICENSE.md, release/packages/syriac_aramaic/README.md, release/packages/syriac_aramaic/source/syriac_aramaic.kps, release/packages/syriac_aramaic/source/welcome/aramaic_hebrew-welcome.htm, release/packages/syriac_aramaic/source/welcome/syriac_arabic-welcome.htm, release/packages/syriac_aramaic/source/welcome/syriac_phonetic-welcome.htm, release/packages/syriac_aramaic/source/welcome/welcome.htm, release/s/syriac_arabic/HISTORY.md, release/s/syriac_arabic/LICENSE.md, release/s/syriac_arabic/README.md, release/s/syriac_arabic/source/readme.htm, release/s/syriac_arabic/source/syriac_arabic.kmn, release/s/syriac_arabic/source/syriac_arabic.kps, release/s/syriac_arabic/source/welcome/welcome.htm, release/s/syriac_phonetic/HISTORY.md, release/s/syriac_phonetic/LICENSE.md, release/s/syriac_phonetic/README.md, release/s/syriac_phonetic/source/syriac_phonetic.kmn, release/s/syriac_phonetic/source/syriac_phonetic.kps
Address 3 Syriac kbds from https://github.com/keymanapp/keyboards/issues/3221
=> [Syriac] Update 3 Syriac keyboards and one package to update language tags

release/gautami/gautami_inditran/source/help/gautami_inditran.php
Fixing superscripts in .php file.
=> gautami_thamizh_tamil.php superscripts

release/gautami/gautami_thamizh_tamil/source/help/gautami_thamizh_tamil.php
Issue detected in help merge PR https://github.com/keymanapp/help.keyman.com/pull/1738
=> chore: fix quote marks in gautami_thamizh_tamil.php

experimental/w/winchus/source/help/winchus.php
Help file isn't displaying properly:
https://help.keyman.com/keyboard/winchus/0.9.7/winchus
Also, the contents seem to be from a previous version of documentation so I pulled in contents from welcome.htm.
html structure is bad, but I didn't attempt to clean that up.
=> [winchus_php] Changes to php to match welcome file and display online

release/s/soqotri_arabic/source/help/soqotri_arabic.php
Attempt to give a better display.
=> [soqotri_php] Update help file for better display

package-lock.json, package.json
One relevant change in 17.0.333:
* fix(developer): filter incorrect fonts out of .keyboard_info (keymanapp/keyman#12913)
=> chore: upgrade to kmc 17.0.333

experimental/t/tengwar_quenya/HISTORY.md, experimental/t/tengwar_quenya/source/tengwar_quenya.kmn, experimental/t/tengwar_quenya/source/tengwar_quenya.kps
#3337 made needed change, but version number wasn't changed.
=> [tengwar_quenya] update version for previous changes

release/sil/sil_mon/HISTORY.md, release/sil/sil_mon/README.md, release/sil/sil_mon/source/sil_mon.kmn, release/sil/sil_mon/source/sil_mon.kps
Follows #3340 and adds web platform so online help OSK is available.
=> [sil_mon] Add web platform

experimental/k/khmer_ldml/HISTORY.md, experimental/k/khmer_ldml/source/khmer_ldml.kps, experimental/k/khmer_ldml/source/khmer_ldml.xml
Follows #3273
Add OSK.png to the keyboard package to fix broken link in welcome.htm
=> [khmer_ldml] Add OSK.png to keyboard package

release/fv/fv_southern_carrier/source/fv_southern_carrier.kmn, release/m/mozhi_malayalam/source/mozhi_malayalam.kmn
=> fix(fv_southern_carrier,mozhi_malayalam): remove `nul` from output where not needed

release/v/vietnam/HISTORY.md, release/v/vietnam/README.md, release/v/vietnam/source/help/vietnam.php, release/v/vietnam/source/readme.htm, release/v/vietnam/source/vietnam.kmn, release/v/vietnam/source/vietnam.kps, release/v/vietnam/source/welcome.htm
=> vietnam updating

release/v/vietnam/HISTORY.md, release/v/vietnam/source/vietnam.kmn, release/v/vietnam/source/vietnam.kps
=> vietnam keyboard updating

release/g/greek_tonizo/source/help/greek_tonizo.php
Fixes broken deployment at https://github.com/keymanapp/help.keyman.com/pull/1967
=> chore(greek_tonizo): fix link to website

experimental/z/zanan/source/help/zanan.php
Fix failed CI action https://github.com/keymanapp/help.keyman.com/actions/runs/14249999804/job/39940265056
=> [zanan] Fix page name in help

release/e/eo_plus/source/help/eo_plus.php, release/gff/gff_ethiopic/source/help/gff_ethiopic.php
I'm just doing this for two help files to see if I have the syntax correct.
If correct, there are 41 other keyboards with the same issue.
=> [php_head] Move head css into php header

experimental/h/hindi_flick/source/help/hindi_flick.php
Online help had poor display because there was a missing `</div>`.
=> [hindi_flick] Update php file to have closing div

release/nlci/nlci_gujarati_winscript/source/help/nlci_gujarati_winscript.php, release/r/remington_gail/source/help/remington_gail.php, release/sil/sil_korda_jamo/source/help/sil_korda_jamo.php, release/sil/sil_korda_latin/source/help/sil_korda_latin.php, release/sil/sil_senegal_bqj_azerty/source/help/sil_senegal_bqj_azerty.php
A few of the keyboards that need fixing. If this works, I'll do all the Senegal ones next.
=> [php_head] Attempt to fix some of the php head and css elements

release/g/gondi_dev/source/help/gondi_dev.php
Fixes help deployment fail on https://github.com/keymanapp/help.keyman.com/actions/runs/14715278035/job/41297103574
coming out of #3469 
> PHP Parse error:  syntax error, unexpected end of file, expecting variable or heredoc end or "${" or "{$" in ./keyboard/gondi_dev/1.1.2/gondi_dev.php on line 269
=> [gondi_dev] Fix heredoc END in help file

release/g/gondi_gunjala/source/help/gondi_gunjala.php, release/g/gondi_gunjala_inscript/source/help/gondi_gunjala_inscript.php, release/g/gondi_tel/source/help/gondi_tel.php, release/p/pukapuka/source/help/pukapuka.php
Follows #3469 and #3470
Attempting to fix remaining heredoc syntax for other PHP files.
Affecting help deployment https://github.com/keymanapp/help.keyman.com/actions/runs/14722448206/job/41318603973
> PHP Parse error:  syntax error, unexpected end of file, expecting variable or heredoc end or "${" or "{$" in ./keyboard/gondi_gunjala/1.1.3/gondi_gunjala.php on line 131
xargs: php: exited with status 255; aborting
=> attempt to fix remaining heredoc syntax

resources/build_targets.inc.sh
=> fix: use extended regex instead of Perl regex to support Apple grep

release/nlci/nlci_oriya_winscript/source/help/nlci_oriya_winscript.php
Follows #3469 (hopefully got them all now)
This fixes the heredoc indentation. And also restores the closing comment originally from
https://github.com/keymanapp/keyboards/pull/3469/files#diff-8e9ab4bfa2b48563bf5743cd433d000b9141a08d10dfa49e6d2047fea5a89fc5
=> [nlci_oriya_winscript] Fix heredoc indentation and revert closing comment

release/c/cs_pinyin/HISTORY.md, release/c/cs_pinyin/source/cs_pinyin.kmn
=> fix(cs_pinyin): runs only on Windows

release/packages/fv_all/HISTORY.md, release/packages/fv_all/source/fv_all.kps.in
Addresses #3478 in incrementing fv_all.kmp
=> [fv_all] Rebuild inuktitut_pirurvik

release/t/triqui_itunyoso/HISTORY.md, release/t/triqui_itunyoso/LICENSE.md, release/t/triqui_itunyoso/source/triqui_itunyoso.kmn, release/t/triqui_itunyoso/source/triqui_itunyoso.kps, release/t/triqui_itunyoso/source/welcome.htm
When the font was added previously the versioning was not set properly in the .kps.
FYI: @kaylashames
=> [triqui_itunyoso] Force version bump

experimental/b/bidayuh/source/help/bidayuh.php, experimental/s/salako_rara/source/help/salako_rara.php
@Nnyny added online help files for most recent keyboards added to experimental.
=> [add_php] Add help files for two experimental keyboards

release/g/greek_tonizo/source/greek_tonizo.kmn
I had forgotten to update the version number
=> Reloaded keyboard source file

experimental/s/soninke_n_ti/source/help/soninke_n_ti.php
Fixes help deployment fail on keymanapp/help.keyman.com#2091
=> [soninke_n_ti] Fix apostrophe in help file

release/gff/gff_mesobe_fidelat/HISTORY.md, release/gff/gff_mesobe_fidelat/LICENSE.md, release/gff/gff_mesobe_fidelat/source/gff_mesobe_fidelat.css, release/gff/gff_mesobe_fidelat/source/gff_mesobe_fidelat.keyman-touch-layout, release/gff/gff_mesobe_fidelat/source/gff_mesobe_fidelat.kmn
This is the GFF Mesobe Fidelat v1.1.2:
* CSS fixes for K_SHIFT keys.
=> GFF Mesobe Fidelat v1.1.2

release/m/modi_kagapa_phonetic/source/help/modi_kagapa_phonetic.php
=> [modi_kagapa_phonetic] Fix help file to not mix tabs and spaces

experimental/h/hong_kong/HISTORY.md, experimental/h/hong_kong/source/help/hong_kong.php, experimental/h/hong_kong/source/hong_kong.kmn, experimental/h/hong_kong/source/hong_kong.kps, experimental/h/hong_kong/source/welcome.htm
=> Hong Kong keyboard updating

release/sil/sil_hupdah/source/help/sil_hupdah.php
follow: #3706. 
This PR is ready for review, Lorna.
Thank you.
=> [sil_hupdah] another try to fix the table in help doc

experimental/l/lao_pali_extended/source/help/lao_pali_extended.php, release/a/aksarabali_panlex/source/help/aksarabali_panlex.php, release/b/burushaski_girminas_perso_arabic/source/help/burushaski_girminas_perso_arabic.php, release/g/greekclassical/source/help/greekclassical.php, release/h/ho_latin/source/help/ho_latin.php, release/k/kmhmu_2008/source/help/kmhmu_2008.php, release/k/korean_rr/source/help/korean_rr.php, release/l/lao_2008_basic/source/help/lao_2008_basic.php, release/l/lao_2008_rapid/source/help/lao_2008_rapid.php, release/l/lao_pali/source/help/lao_pali.php, release/l/lao_pali_us/source/help/lao_pali_us.php, release/l/lao_phonetic/source/help/lao_phonetic.php, release/m/masaram_gondi/source/help/masaram_gondi.php, release/n/nko/source/help/nko.php, release/r/rawang/source/help/rawang.php, release/sil/sil_brao/source/help/sil_brao.php, release/sil/sil_kmhmu/source/help/sil_kmhmu.php, release/sil/sil_yoruba8/source/help/sil_yoruba8.php, release/t/tawallammat_latin/source/help/tawallammat_latin.php, release/t/tibetan_direct_input/source/help/tibetan_direct_input.php
It looks like sometimes I recommended people use `$style` instead of `$pagestyle` which affects whether the correct font (and table settings) are used.
=> [php_pagestyle] Have been using wrong command in php files
